/*
 * Copyright (c) 2014-2018 T-Systems Multimedia Solutions GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.tsystems.mms.apm.performancesignature.dynatracesaas.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import hudson.Extension;
import hudson.model.AbstractDescribableImpl;
import hudson.model.Descriptor;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.kohsuke.stapler.DataBoundConstructor;
import org.kohsuke.stapler.DataBoundSetter;

import javax.annotation.Nonnull;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * Allows to attach an event to an entity that fits the specified criteria
 */
@ApiModel(description = "Allows to attach an event to an entity that fits the specified criteria")

public class TagMatchRule extends AbstractDescribableImpl<TagMatchRule> {
    @SerializedName("meTypes")
    private List<MeTypesEnum> meTypes;
    @SerializedName("tags")
    private List<TagInfo> tags;

    @DataBoundConstructor
    public TagMatchRule() {
    }

    public TagMatchRule meTypes(List<MeTypesEnum> meTypes) {
        this.meTypes = meTypes;
        return this;
    }

    public TagMatchRule addMeTypesItem(MeTypesEnum meTypesItem) {
        if (this.meTypes == null) {
            this.meTypes = new ArrayList<>();
        }
        this.meTypes.add(meTypesItem);
        return this;
    }

    /**
     * List of ME types the event can be attached to
     *
     * @return meTypes
     **/
    @ApiModelProperty(value = "List of ME types the event can be attached to")
    public List<MeTypesEnum> getMeTypesEnum() {
        return meTypes;
    }

    public void setMeTypesEnum(List<MeTypesEnum> meTypes) {
        this.meTypes = meTypes;
    }

    public List<MeType> getMeTypes() {
        if (meTypes == null) return new ArrayList<>();
        return meTypes.stream().map(meType -> new MeType(meType.getValue())).collect(Collectors.toList());
    }

    @DataBoundSetter
    public void setMeTypes(List<MeType> meTypes) {
        this.meTypes = meTypes.stream().map(text -> MeTypesEnum.fromValue(text.getMeType())).collect(Collectors.toList());
    }

    public TagMatchRule tags(List<TagInfo> tags) {
        this.tags = tags;
        return this;
    }

    public TagMatchRule addTagsItem(TagInfo tagsItem) {
        if (this.tags == null) {
            this.tags = new ArrayList<>();
        }
        this.tags.add(tagsItem);
        return this;
    }

    /**
     * List of Tags an entity has to match
     *
     * @return tags
     **/
    @ApiModelProperty(value = "List of Tags an entity has to match")
    public List<TagInfo> getTags() {
        return tags;
    }

    @DataBoundSetter
    public void setTags(List<TagInfo> tags) {
        this.tags = tags;
    }

    @Override
    public String toString() {
        return "class TagMatchRule {\n" +
                "    meTypes: " + toIndentedString(meTypes) + "\n" +
                "    tags: " + toIndentedString(tags) + "\n" +
                "}";
    }

    /**
     * Gets or Sets meTypes
     */
    @JsonAdapter(MeTypesEnum.Adapter.class)
    public enum MeTypesEnum {
        APPLICATION("APPLICATION"),
        APPLICATION_METHOD("APPLICATION_METHOD"),
        AUXILIARY_SYNTHETIC_TEST("AUXILIARY_SYNTHETIC_TEST"),
        AWS_AVAILABILITY_ZONE("AWS_AVAILABILITY_ZONE"),
        AWS_LAMBDA_FUNCTION("AWS_LAMBDA_FUNCTION"),
        AZURE_API_MANAGEMENT_SERVICE("AZURE_API_MANAGEMENT_SERVICE"),
        AZURE_APPLICATION_GATEWAY("AZURE_APPLICATION_GATEWAY"),
        AZURE_EVENT_HUB("AZURE_EVENT_HUB"),
        AZURE_LOAD_BALANCER("AZURE_LOAD_BALANCER"),
        AZURE_REDIS_CACHE("AZURE_REDIS_CACHE"),
        AZURE_REGION("AZURE_REGION"),
        AZURE_SQL_SERVER("AZURE_SQL_SERVER"),
        AZURE_VM("AZURE_VM"),
        CINDER_VOLUME("CINDER_VOLUME"),
        CUSTOM_APPLICATION("CUSTOM_APPLICATION"),
        CUSTOM_DEVICE("CUSTOM_DEVICE"),
        CUSTOM_DEVICE_GROUP("CUSTOM_DEVICE_GROUP"),
        DCRUM_APPLICATION("DCRUM_APPLICATION"),
        DCRUM_SERVICE("DCRUM_SERVICE"),
        DCRUM_SERVICE_INSTANCE("DCRUM_SERVICE_INSTANCE"),
        DISK("DISK"),
        DOCKER_CONTAINER_GROUP_INSTANCE("DOCKER_CONTAINER_GROUP_INSTANCE"),
        DYNAMO_DB_TABLE("DYNAMO_DB_TABLE"),
        EBS_VOLUME("EBS_VOLUME"),
        EC2_INSTANCE("EC2_INSTANCE"),
        ELASTIC_LOAD_BALANCER("ELASTIC_LOAD_BALANCER"),
        ENVIRONMENT("ENVIRONMENT"),
        GEOLOCATION("GEOLOCATION"),
        GEOLOC_SITE("GEOLOC_SITE"),
        GOOGLE_COMPUTE_ENGINE("GOOGLE_COMPUTE_ENGINE"),
        HOST("HOST"),
        HOST_GROUP("HOST_GROUP"),
        HYPERVISOR("HYPERVISOR"),
        MOBILE_APPLICATION("MOBILE_APPLICATION"),
        NETWORK_INTERFACE("NETWORK_INTERFACE"),
        NEUTRON_SUBNET("NEUTRON_SUBNET"),
        OPENSTACK_PROJECT("OPENSTACK_PROJECT"),
        OPENSTACK_REGION("OPENSTACK_REGION"),
        OPENSTACK_VM("OPENSTACK_VM"),
        OS("OS"),
        PROCESS_GROUP("PROCESS_GROUP"),
        PROCESS_GROUP_INSTANCE("PROCESS_GROUP_INSTANCE"),
        RELATIONAL_DATABASE_SERVICE("RELATIONAL_DATABASE_SERVICE"),
        SERVICE("SERVICE"),
        SERVICE_INSTANCE("SERVICE_INSTANCE"),
        SERVICE_METHOD("SERVICE_METHOD"),
        SWIFT_CONTAINER("SWIFT_CONTAINER"),
        SYNTHETIC_TEST("SYNTHETIC_TEST"),
        SYNTHETIC_TEST_STEP("SYNTHETIC_TEST_STEP"),
        VIRTUALMACHINE("VIRTUALMACHINE"),
        VMWARE_DATACENTER("VMWARE_DATACENTER");

        private final String value;

        MeTypesEnum(String value) {
            this.value = value;
        }

        public static MeTypesEnum fromValue(String text) {
            return Arrays.stream(MeTypesEnum.values()).filter(b -> b.value.equals(text)).findFirst().orElse(null);
        }

        public String getValue() {
            return value;
        }

        @Override
        public String toString() {
            return value;
        }

        public static class Adapter extends TypeAdapter<MeTypesEnum> {
            @Override
            public void write(final JsonWriter jsonWriter, final MeTypesEnum enumeration) throws IOException {
                jsonWriter.value(enumeration.getValue());
            }

            @Override
            public MeTypesEnum read(final JsonReader jsonReader) throws IOException {
                String value = jsonReader.nextString();
                return MeTypesEnum.fromValue(value);
            }
        }
    }

    @Extension
    public static class DescriptorImpl extends Descriptor<TagMatchRule> {
        @Nonnull
        @Override
        public String getDisplayName() {
            return "";
        }
    }

}

