/*
 * Dynatrace Environment API
 *  Documentation of the Dynatrace Environment API v2. Resources here generally supersede those in v1. Migration of resources from v1 is in progress.   If you miss a resource, consider using the Dynatrace Environment API v1. To read about use cases and examples, see [Dynatrace Documentation](https://dt-url.net/2u23k1k) .  Notes about compatibility: * Operations marked as early adopter or preview may be changed in non-compatible ways, although we try to avoid this. * We may add new enum constants without incrementing the API version; thus, clients need to handle unknown enum constants gracefully.
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.env2.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.io.IOException;
import java.util.Objects;

/**
 * The dimension of a metric.
 */
@ApiModel(description = "The dimension of a metric.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class MetricDimensionDefinition {
  public static final String SERIALIZED_NAME_NAME = "name";
  public static final String SERIALIZED_NAME_KEY = "key";
  public static final String SERIALIZED_NAME_TYPE = "type";
  public static final String SERIALIZED_NAME_DISPLAY_NAME = "displayName";
  public static final String SERIALIZED_NAME_INDEX = "index";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;
  @SerializedName(SERIALIZED_NAME_KEY)
  private String key;
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;
  @SerializedName(SERIALIZED_NAME_DISPLAY_NAME)
  private String displayName;
  @SerializedName(SERIALIZED_NAME_INDEX)
  private Integer index;

  public MetricDimensionDefinition name(String name) {

    this.name = name;
    return this;
  }

  /**
   * The name of the dimension.
   *
   * @return name
   **/
  @ApiModelProperty(required = true, value = "The name of the dimension.")

  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public MetricDimensionDefinition key(String key) {

    this.key = key;
    return this;
  }

  /**
   * The key of the dimension.    It must be unique within the metric.
   *
   * @return key
   **/
  @ApiModelProperty(required = true, value = "The key of the dimension.    It must be unique within the metric.")

  public String getKey() {
    return key;
  }

  public void setKey(String key) {
    this.key = key;
  }

  public MetricDimensionDefinition type(TypeEnum type) {

    this.type = type;
    return this;
  }

  /**
   * The type of the dimension.
   *
   * @return type
   **/
  @ApiModelProperty(required = true, value = "The type of the dimension.")

  public TypeEnum getType() {
    return type;
  }

  public void setType(TypeEnum type) {
    this.type = type;
  }

  public MetricDimensionDefinition displayName(String displayName) {

    this.displayName = displayName;
    return this;
  }

  /**
   * The display name of the dimension.
   *
   * @return displayName
   **/
  @ApiModelProperty(required = true, value = "The display name of the dimension.")

  public String getDisplayName() {
    return displayName;
  }

  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public MetricDimensionDefinition index(Integer index) {

    this.index = index;
    return this;
  }

  /**
   * The unique 0-based index of the dimension.    Appending transformations such as :names or :parents may change the indexes of dimensions. &#x60;null&#x60; is used for the dimensions of a metric with flexible dimensions, which can be referenced with their dimension key, but do not have an intrinsic order that could be used for the index.
   *
   * @return index
   **/
  @ApiModelProperty(required = true, value = "The unique 0-based index of the dimension.    Appending transformations such as :names or :parents may change the indexes of dimensions. `null` is used for the dimensions of a metric with flexible dimensions, which can be referenced with their dimension key, but do not have an intrinsic order that could be used for the index.")

  public Integer getIndex() {
    return index;
  }

  public void setIndex(Integer index) {
    this.index = index;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MetricDimensionDefinition metricDimensionDefinition = (MetricDimensionDefinition) o;
    return Objects.equals(this.name, metricDimensionDefinition.name) &&
            Objects.equals(this.key, metricDimensionDefinition.key) &&
            Objects.equals(this.type, metricDimensionDefinition.type) &&
            Objects.equals(this.displayName, metricDimensionDefinition.displayName) &&
            Objects.equals(this.index, metricDimensionDefinition.index);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, key, type, displayName, index);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MetricDimensionDefinition {\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    key: ").append(toIndentedString(key)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * The type of the dimension.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    ENTITY("ENTITY"),

    NUMBER("NUMBER"),

    OTHER("OTHER"),

    STRING("STRING"),

    VOID("VOID");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

}

