/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.HashMap;
import java.util.Map;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * EventPushMessage
 */

public class EventPushMessage {
    @SerializedName("eventType")
    private EventTypeEnum eventType = null;
    @SerializedName("start")
    private Long start = null;
    @SerializedName("end")
    private Long end = null;
    @SerializedName("attachRules")
    private PushEventAttachRules attachRules = null;
    @SerializedName("customProperties")
    private Map<String, Object> customProperties = null;

    public EventPushMessage eventType(EventTypeEnum eventType) {
        this.eventType = eventType;
        return this;
    }

    /**
     * The predefined event type
     *
     * @return eventType
     **/
    @ApiModelProperty(value = "The predefined event type")
    public EventTypeEnum getEventType() {
        return eventType;
    }

    public void setEventType(EventTypeEnum eventType) {
        this.eventType = eventType;
    }

    public EventPushMessage start(Long start) {
        this.start = start;
        return this;
    }

    /**
     * Optional start timestamp of the event in UTC milliseconds (for example 1495200637630). The actual time is used for the event if no start timestamp is provided.
     *
     * @return start
     **/
    @ApiModelProperty(value = "Optional start timestamp of the event in UTC milliseconds (for example 1495200637630). The actual time is used for the event if no start timestamp is provided.")
    public Long getStart() {
        return start;
    }

    public void setStart(Long start) {
        this.start = start;
    }

    public EventPushMessage end(Long end) {
        this.end = end;
        return this;
    }

    /**
     * Optional end timestamp of the event in UTC milliseconds. The actual time is used if no end timestamp is provided.
     *
     * @return end
     **/
    @ApiModelProperty(value = "Optional end timestamp of the event in UTC milliseconds. The actual time is used if no end timestamp is provided.")
    public Long getEnd() {
        return end;
    }

    public void setEnd(Long end) {
        this.end = end;
    }

    public EventPushMessage attachRules(PushEventAttachRules attachRules) {
        this.attachRules = attachRules;
        return this;
    }

    /**
     * contains attachment rules
     *
     * @return attachRules
     **/
    @ApiModelProperty(value = "contains attachment rules")
    public PushEventAttachRules getAttachRules() {
        return attachRules;
    }

    public void setAttachRules(PushEventAttachRules attachRules) {
        this.attachRules = attachRules;
    }

    public EventPushMessage customProperties(Map<String, Object> customProperties) {
        this.customProperties = customProperties;
        return this;
    }

    public EventPushMessage putCustomPropertiesItem(String key, Object customPropertiesItem) {
        if (this.customProperties == null) {
            this.customProperties = new HashMap<>();
        }
        this.customProperties.put(key, customPropertiesItem);
        return this;
    }

    /**
     * Dictionary of custom key value pairs that can be used to send additional information along with the event
     *
     * @return customProperties
     **/
    @ApiModelProperty(value = "Dictionary of custom key value pairs that can be used to send additional information along with the event")
    public Map<String, Object> getCustomProperties() {
        return customProperties;
    }

    public void setCustomProperties(Map<String, Object> customProperties) {
        this.customProperties = customProperties;
    }

    @Override
    public String toString() {
        return "class EventPushMessage {\n" +
                "    eventType: " + toIndentedString(eventType) + "\n" +
                "    start: " + toIndentedString(start) + "\n" +
                "    end: " + toIndentedString(end) + "\n" +
                "    attachRules: " + toIndentedString(attachRules) + "\n" +
                "    customProperties: " + toIndentedString(customProperties) + "\n" +
                "}";
    }
}

