/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * ExternalSyntheticLocationTestResult
 */

public class ExternalSyntheticLocationTestResult {
    @SerializedName("id")
    private String id;

    @SerializedName("startTimestamp")
    private Long startTimestamp;

    @SerializedName("success")
    private Boolean success;

    @SerializedName("responseTimeMillis")
    private Long responseTimeMillis;

    @SerializedName("stepResults")
    private List<SyntheticTestStepResult> stepResults = new ArrayList<>();

    @SerializedName("successRate")
    private Double successRate;

    public ExternalSyntheticLocationTestResult id(String id) {
        this.id = id;
        return this;
    }

    /**
     * The location&#39;s unique id.
     *
     * @return id
     **/
    @ApiModelProperty(required = true, value = "The location's unique id.")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ExternalSyntheticLocationTestResult startTimestamp(Long startTimestamp) {
        this.startTimestamp = startTimestamp;
        return this;
    }

    /**
     * Timestamp in millis UTC Dynatrace cluster time when the test was executed on this location.
     *
     * @return startTimestamp
     **/
    @ApiModelProperty(required = true, value = "Timestamp in millis UTC Dynatrace cluster time when the test was executed on this location.")
    public Long getStartTimestamp() {
        return startTimestamp;
    }

    public void setStartTimestamp(Long startTimestamp) {
        this.startTimestamp = startTimestamp;
    }

    public ExternalSyntheticLocationTestResult success(Boolean success) {
        this.success = success;
        return this;
    }

    /**
     * Indicates if the execution of the step should be seen as successful - will influence availability timeseries.
     *
     * @return success
     **/
    @ApiModelProperty(required = true, value = "Indicates if the execution of the step should be seen as successful - will influence availability timeseries.")
    public Boolean isSuccess() {
        return success;
    }

    public void setSuccess(Boolean success) {
        this.success = success;
    }

    public ExternalSyntheticLocationTestResult responseTimeMillis(Long responseTimeMillis) {
        this.responseTimeMillis = responseTimeMillis;
        return this;
    }

    /**
     * The overall response time of the test on this location in milliseconds. When absent, calculated as the sum of response times of all steps.
     *
     * @return responseTimeMillis
     **/
    @ApiModelProperty(value = "The overall response time of the test on this location in milliseconds. When absent, calculated as the sum of response times of all steps.")
    public Long getResponseTimeMillis() {
        return responseTimeMillis;
    }

    public void setResponseTimeMillis(Long responseTimeMillis) {
        this.responseTimeMillis = responseTimeMillis;
    }

    public ExternalSyntheticLocationTestResult stepResults(List<SyntheticTestStepResult> stepResults) {
        this.stepResults = stepResults;
        return this;
    }

    public ExternalSyntheticLocationTestResult addStepResultsItem(SyntheticTestStepResult stepResultsItem) {
        this.stepResults.add(stepResultsItem);
        return this;
    }

    /**
     * One or more step results within a synthetic test.
     *
     * @return stepResults
     **/
    @ApiModelProperty(required = true, value = "One or more step results within a synthetic test.")
    public List<SyntheticTestStepResult> getStepResults() {
        return stepResults;
    }

    public void setStepResults(List<SyntheticTestStepResult> stepResults) {
        this.stepResults = stepResults;
    }

    public ExternalSyntheticLocationTestResult successRate(Double successRate) {
        this.successRate = successRate;
        return this;
    }

    /**
     * The overall availability of this test on this location in percent. When absent, calculated as the number of successful steps versus number of failed steps.
     *
     * @return successRate
     **/
    @ApiModelProperty(value = "The overall availability of this test on this location in percent. When absent, calculated as the number of successful steps versus number of failed steps.")
    public Double getSuccessRate() {
        return successRate;
    }

    public void setSuccessRate(Double successRate) {
        this.successRate = successRate;
    }

    @Override
    public String toString() {
        return "class ExternalSyntheticLocationTestResult {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    startTimestamp: " + toIndentedString(startTimestamp) + "\n" +
                "    success: " + toIndentedString(success) + "\n" +
                "    responseTimeMillis: " + toIndentedString(responseTimeMillis) + "\n" +
                "    stepResults: " + toIndentedString(stepResults) + "\n" +
                "    successRate: " + toIndentedString(successRate) + "\n" +
                "}";
    }
}

