/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * Pushes updates on open events to Dynatrace or closes previously open events.
 */
@ApiModel(description = "Pushes updates on open events to Dynatrace or closes previously open events.")

public class ExternalSyntheticEvents {
    @SerializedName("syntheticEngineName")
    private String syntheticEngineName = null;

    @SerializedName("open")
    private List<ExternalEventOpenNotification> open = null;

    @SerializedName("resolved")
    private List<ExternalEventResolvedNotification> resolved = null;

    public ExternalSyntheticEvents syntheticEngineName(String syntheticEngineName) {
        this.syntheticEngineName = syntheticEngineName;
        return this;
    }

    /**
     * Synthetic engine name.
     *
     * @return syntheticEngineName
     **/
    @ApiModelProperty(value = "Synthetic engine name.")
    public String getSyntheticEngineName() {
        return syntheticEngineName;
    }

    public void setSyntheticEngineName(String syntheticEngineName) {
        this.syntheticEngineName = syntheticEngineName;
    }

    public ExternalSyntheticEvents open(List<ExternalEventOpenNotification> open) {
        this.open = open;
        return this;
    }

    public ExternalSyntheticEvents addOpenItem(ExternalEventOpenNotification openItem) {
        if (this.open == null) {
            this.open = new ArrayList<>();
        }
        this.open.add(openItem);
        return this;
    }

    /**
     * Set of open events.
     *
     * @return open
     **/
    @ApiModelProperty(value = "Set of open events.")
    public List<ExternalEventOpenNotification> getOpen() {
        return open;
    }

    public void setOpen(List<ExternalEventOpenNotification> open) {
        this.open = open;
    }

    public ExternalSyntheticEvents resolved(List<ExternalEventResolvedNotification> resolved) {
        this.resolved = resolved;
        return this;
    }

    public ExternalSyntheticEvents addResolvedItem(ExternalEventResolvedNotification resolvedItem) {
        if (this.resolved == null) {
            this.resolved = new ArrayList<>();
        }
        this.resolved.add(resolvedItem);
        return this;
    }

    /**
     * Set of resolved events.
     *
     * @return resolved
     **/
    @ApiModelProperty(value = "Set of resolved events.")
    public List<ExternalEventResolvedNotification> getResolved() {
        return resolved;
    }

    public void setResolved(List<ExternalEventResolvedNotification> resolved) {
        this.resolved = resolved;
    }

    @Override
    public String toString() {
        return "class ExternalSyntheticEvents {\n" +
                "    syntheticEngineName: " + toIndentedString(syntheticEngineName) + "\n" +
                "    open: " + toIndentedString(open) + "\n" +
                "    resolved: " + toIndentedString(resolved) + "\n" +
                "}";
    }
}

