/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * ExternalSyntheticTests
 */

public class ExternalSyntheticTests {
    @SerializedName("syntheticEngineName")
    private String syntheticEngineName;

    @SerializedName("syntheticEngineIconUrl")
    private String syntheticEngineIconUrl;

    @SerializedName("messageTimestamp")
    private Long messageTimestamp;

    @SerializedName("locations")
    private List<SyntheticLocation> locations;

    @SerializedName("tests")
    private List<ExternalSyntheticTest> tests;

    @SerializedName("testResults")
    private List<ExternalSyntheticTestResult> testResults;

    @SerializedName("syntheticEngine")
    private Integer syntheticEngine;

    public ExternalSyntheticTests syntheticEngineName(String syntheticEngineName) {
        this.syntheticEngineName = syntheticEngineName;
        return this;
    }

    /**
     * Synthetic engine name.
     *
     * @return syntheticEngineName
     **/
    @ApiModelProperty(value = "Synthetic engine name.")
    public String getSyntheticEngineName() {
        return syntheticEngineName;
    }

    public void setSyntheticEngineName(String syntheticEngineName) {
        this.syntheticEngineName = syntheticEngineName;
    }

    public ExternalSyntheticTests syntheticEngineIconUrl(String syntheticEngineIconUrl) {
        this.syntheticEngineIconUrl = syntheticEngineIconUrl;
        return this;
    }

    /**
     * Synthetic engine icon URL.
     *
     * @return syntheticEngineIconUrl
     **/
    @ApiModelProperty(value = "Synthetic engine icon URL.")
    public String getSyntheticEngineIconUrl() {
        return syntheticEngineIconUrl;
    }

    public void setSyntheticEngineIconUrl(String syntheticEngineIconUrl) {
        this.syntheticEngineIconUrl = syntheticEngineIconUrl;
    }

    public ExternalSyntheticTests messageTimestamp(Long messageTimestamp) {
        this.messageTimestamp = messageTimestamp;
        return this;
    }

    /**
     * Timestamp of when the message was created.
     *
     * @return messageTimestamp
     **/
    @ApiModelProperty(required = true, value = "Timestamp of when the message was created.")
    public Long getMessageTimestamp() {
        return messageTimestamp;
    }

    public void setMessageTimestamp(Long messageTimestamp) {
        this.messageTimestamp = messageTimestamp;
    }

    public ExternalSyntheticTests locations(List<SyntheticLocation> locations) {
        this.locations = locations;
        return this;
    }

    public ExternalSyntheticTests addLocationsItem(SyntheticLocation locationsItem) {
        if (this.locations == null) {
            this.locations = new ArrayList<>();
        }
        this.locations.add(locationsItem);
        return this;
    }

    /**
     * Test site id definitions and metainfos on test sites.
     *
     * @return locations
     **/
    @ApiModelProperty(value = "Test site id definitions and metainfos on test sites.")
    public List<SyntheticLocation> getLocations() {
        return locations;
    }

    public void setLocations(List<SyntheticLocation> locations) {
        this.locations = locations;
    }

    public ExternalSyntheticTests tests(List<ExternalSyntheticTest> tests) {
        this.tests = tests;
        return this;
    }

    public ExternalSyntheticTests addTestsItem(ExternalSyntheticTest testsItem) {
        if (this.tests == null) {
            this.tests = new ArrayList<>();
        }
        this.tests.add(testsItem);
        return this;
    }

    /**
     * a set of tests
     *
     * @return tests
     **/
    @ApiModelProperty(value = "a set of tests")
    public List<ExternalSyntheticTest> getTests() {
        return tests;
    }

    public void setTests(List<ExternalSyntheticTest> tests) {
        this.tests = tests;
    }

    public ExternalSyntheticTests testResults(List<ExternalSyntheticTestResult> testResults) {
        this.testResults = testResults;
        return this;
    }

    public ExternalSyntheticTests addTestResultsItem(ExternalSyntheticTestResult testResultsItem) {
        if (this.testResults == null) {
            this.testResults = new ArrayList<>();
        }
        this.testResults.add(testResultsItem);
        return this;
    }

    /**
     * Array of one or more synthetic test run results.
     *
     * @return testResults
     **/
    @ApiModelProperty(value = "Array of one or more synthetic test run results.")
    public List<ExternalSyntheticTestResult> getTestResults() {
        return testResults;
    }

    public void setTestResults(List<ExternalSyntheticTestResult> testResults) {
        this.testResults = testResults;
    }

    public ExternalSyntheticTests syntheticEngine(Integer syntheticEngine) {
        this.syntheticEngine = syntheticEngine;
        return this;
    }

    /**
     * Synthetic engine serial.
     *
     * @return syntheticEngine
     **/
    @ApiModelProperty(value = "Synthetic engine serial.")
    public Integer getSyntheticEngine() {
        return syntheticEngine;
    }

    public void setSyntheticEngine(Integer syntheticEngine) {
        this.syntheticEngine = syntheticEngine;
    }

    @Override
    public String toString() {
        return "class ExternalSyntheticTests {\n" +
                "    syntheticEngineName: " + toIndentedString(syntheticEngineName) + "\n" +
                "    syntheticEngineIconUrl: " + toIndentedString(syntheticEngineIconUrl) + "\n" +
                "    messageTimestamp: " + toIndentedString(messageTimestamp) + "\n" +
                "    locations: " + toIndentedString(locations) + "\n" +
                "    tests: " + toIndentedString(tests) + "\n" +
                "    testResults: " + toIndentedString(testResults) + "\n" +
                "    syntheticEngine: " + toIndentedString(syntheticEngine) + "\n" +
                "}";
    }
}

