/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * Count of open problems in your environment.
 */
@ApiModel(description = "Count of open problems in your environment.")

public class GlobalProblemStatus {
    @SerializedName("totalOpenProblemsCount")
    private Integer totalOpenProblemsCount = null;

    @SerializedName("openProblemCounts")
    private GlobalProblemStatusOpenProblemCounts openProblemCounts = null;

    public GlobalProblemStatus totalOpenProblemsCount(Integer totalOpenProblemsCount) {
        this.totalOpenProblemsCount = totalOpenProblemsCount;
        return this;
    }

    /**
     * Total number of open problems in your environment.
     *
     * @return totalOpenProblemsCount
     **/
    @ApiModelProperty(value = "Total number of open problems in your environment.")
    public Integer getTotalOpenProblemsCount() {
        return totalOpenProblemsCount;
    }

    public void setTotalOpenProblemsCount(Integer totalOpenProblemsCount) {
        this.totalOpenProblemsCount = totalOpenProblemsCount;
    }

    public GlobalProblemStatus openProblemCounts(GlobalProblemStatusOpenProblemCounts openProblemCounts) {
        this.openProblemCounts = openProblemCounts;
        return this;
    }

    /**
     * Get openProblemCounts
     *
     * @return openProblemCounts
     **/
    @ApiModelProperty()
    public GlobalProblemStatusOpenProblemCounts getOpenProblemCounts() {
        return openProblemCounts;
    }

    public void setOpenProblemCounts(GlobalProblemStatusOpenProblemCounts openProblemCounts) {
        this.openProblemCounts = openProblemCounts;
    }

    @Override
    public String toString() {
        return "class GlobalProblemStatus {\n" +
                "    totalOpenProblemsCount: " + toIndentedString(totalOpenProblemsCount) + "\n" +
                "    openProblemCounts: " + toIndentedString(openProblemCounts) + "\n" +
                "}";
    }
}

