/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * List of comments to a problem
 */
@ApiModel(description = "List of comments to a problem")

public class ProblemCommentList {
    @SerializedName("comments")
    private List<ProblemComment> comments;

    public ProblemCommentList comments(List<ProblemComment> comments) {
        this.comments = comments;
        return this;
    }

    public ProblemCommentList addCommentsItem(ProblemComment commentsItem) {
        if (this.comments == null) {
            this.comments = new ArrayList<>();
        }
        this.comments.add(commentsItem);
        return this;
    }

    /**
     * List of comments to a problem.
     *
     * @return comments
     **/
    @ApiModelProperty(value = "List of comments to a problem.")
    public List<ProblemComment> getComments() {
        return comments;
    }

    public void setComments(List<ProblemComment> comments) {
        this.comments = comments;
    }

    @Override
    public String toString() {
        return "class ProblemCommentList {\n" +
                "    comments: " + toIndentedString(comments) + "\n" +
                "}";
    }
}

