/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * A comment of a problem
 */
@ApiModel(description = "A comment of a problem")

public class ProblemComment {
    @SerializedName("comment")
    private String comment = null;

    @SerializedName("user")
    private String user = null;

    @SerializedName("context")
    private String context = null;

    public ProblemComment comment(String comment) {
        this.comment = comment;
        return this;
    }

    /**
     * The comment to the problem.
     *
     * @return comment
     **/
    @ApiModelProperty(required = true, value = "The comment to the problem.")
    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public ProblemComment user(String user) {
        this.user = user;
        return this;
    }

    /**
     * The author of the comment.
     *
     * @return user
     **/
    @ApiModelProperty(required = true, value = "The author of the comment.")
    public String getUser() {
        return user;
    }

    public void setUser(String user) {
        this.user = user;
    }

    public ProblemComment context(String context) {
        this.context = context;
        return this;
    }

    /**
     * The context of the comment. It can contain any additional information.
     *
     * @return context
     **/
    @ApiModelProperty(value = "The context of the comment. It can contain any additional information.")
    public String getContext() {
        return context;
    }

    public void setContext(String context) {
        this.context = context;
    }

    @Override
    public String toString() {
        return "class ProblemComment {\n" +
                "    comment: " + toIndentedString(comment) + "\n" +
                "    user: " + toIndentedString(user) + "\n" +
                "    context: " + toIndentedString(context) + "\n" +
                "}";
    }
}

