/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * ProblemFeedResultWrapper
 */

public class ProblemFeedResultWrapper {
    @SerializedName("result")
    private ProblemFeedQueryResult result = null;

    public ProblemFeedResultWrapper result(ProblemFeedQueryResult result) {
        this.result = result;
        return this;
    }

    /**
     * Get result
     *
     * @return result
     **/
    @ApiModelProperty()
    public ProblemFeedQueryResult getResult() {
        return result;
    }

    public void setResult(ProblemFeedQueryResult result) {
        this.result = result;
    }

    @Override
    public String toString() {
        return "class ProblemFeedResultWrapper {\n" +
                "    result: " + toIndentedString(result) + "\n" +
                "}";
    }
}

