/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * ProcessGroupInstanceFromRelationships
 */

public class ProcessGroupInstanceFromRelationships {
    @SerializedName("isProcessOf")
    private List<String> isProcessOf;

    @SerializedName("isInstanceOf")
    private List<String> isInstanceOf;

    @SerializedName("isNetworkClientOf")
    private List<String> isNetworkClientOf;

    public ProcessGroupInstanceFromRelationships isProcessOf(List<String> isProcessOf) {
        this.isProcessOf = isProcessOf;
        return this;
    }

    public ProcessGroupInstanceFromRelationships addIsProcessOfItem(String isProcessOfItem) {
        if (this.isProcessOf == null) {
            this.isProcessOf = new ArrayList<>();
        }
        this.isProcessOf.add(isProcessOfItem);
        return this;
    }

    /**
     * @return isProcessOf
     **/
    public List<String> getIsProcessOf() {
        return isProcessOf;
    }

    public void setIsProcessOf(List<String> isProcessOf) {
        this.isProcessOf = isProcessOf;
    }

    public ProcessGroupInstanceFromRelationships isInstanceOf(List<String> isInstanceOf) {
        this.isInstanceOf = isInstanceOf;
        return this;
    }

    public ProcessGroupInstanceFromRelationships addIsInstanceOfItem(String isInstanceOfItem) {
        if (this.isInstanceOf == null) {
            this.isInstanceOf = new ArrayList<>();
        }
        this.isInstanceOf.add(isInstanceOfItem);
        return this;
    }

    /**
     * @return isInstanceOf
     **/
    public List<String> getIsInstanceOf() {
        return isInstanceOf;
    }

    public void setIsInstanceOf(List<String> isInstanceOf) {
        this.isInstanceOf = isInstanceOf;
    }

    public ProcessGroupInstanceFromRelationships isNetworkClientOf(List<String> isNetworkClientOf) {
        this.isNetworkClientOf = isNetworkClientOf;
        return this;
    }

    public ProcessGroupInstanceFromRelationships addIsNetworkClientOfItem(String isNetworkClientOfItem) {
        if (this.isNetworkClientOf == null) {
            this.isNetworkClientOf = new ArrayList<>();
        }
        this.isNetworkClientOf.add(isNetworkClientOfItem);
        return this;
    }

    /**
     * @return isNetworkClientOf
     **/
    public List<String> getIsNetworkClientOf() {
        return isNetworkClientOf;
    }

    public void setIsNetworkClientOf(List<String> isNetworkClientOf) {
        this.isNetworkClientOf = isNetworkClientOf;
    }

    @Override
    public String toString() {
        return "class ProcessGroupInstanceFromRelationships {\n"
                + "    isProcessOf: " + toIndentedString(isProcessOf) + "\n"
                + "    isInstanceOf: " + toIndentedString(isInstanceOf) + "\n"
                + "    isNetworkClientOf: " + toIndentedString(isNetworkClientOf) + "\n"
                + "}";
    }
}

