/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;
import de.tsystems.mms.apm.performancesignature.dynatracesaas.model.TagInfo;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * ProcessGroup
 */

public class ProcessGroup {
    @SerializedName("entityId")
    private String entityId;

    @SerializedName("displayName")
    private String displayName;

    @SerializedName("customizedName")
    private String customizedName;

    @SerializedName("discoveredName")
    private String discoveredName;

    @SerializedName("firstSeenTimestamp")
    private Long firstSeenTimestamp;

    @SerializedName("lastSeenTimestamp")
    private Long lastSeenTimestamp;

    @SerializedName("tags")
    private List<TagInfo> tags;

    @SerializedName("fromRelationships")
    private ProcessGroupFromRelationships fromRelationships;

    @SerializedName("toRelationships")
    private ProcessGroupToRelationships toRelationships;

    @SerializedName("azureSiteName")
    private List<String> azureSiteName;

    @SerializedName("metadata")
    private ProcessGroupMetadata metadata;

    @SerializedName("softwareTechnologies")
    private List<TechnologyInfo> softwareTechnologies;

    @SerializedName("azureHostName")
    private List<String> azureHostName;

    @SerializedName("listenPorts")
    private List<Integer> listenPorts;

    public ProcessGroup entityId(String entityId) {
        this.entityId = entityId;
        return this;
    }

    /**
     * Dynatrace entity ID of the required entity.   You can find them in the URL of the corresponding Dynatrace page, for example, &#x60;HOST-007&#x60;.
     *
     * @return entityId
     **/
    @ApiModelProperty(value = "Dynatrace entity ID of the required entity.   You can find them in the URL of the corresponding Dynatrace page, for example, `HOST-007`.")
    public String getEntityId() {
        return entityId;
    }

    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }

    public ProcessGroup displayName(String displayName) {
        this.displayName = displayName;
        return this;
    }

    /**
     * The name of the Dynatrace entity, displayed in the UI.
     *
     * @return displayName
     **/
    @ApiModelProperty(value = "The name of the Dynatrace entity, displayed in the UI.")
    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public ProcessGroup customizedName(String customizedName) {
        this.customizedName = customizedName;
        return this;
    }

    /**
     * Customized name of the entity
     *
     * @return customizedName
     **/
    @ApiModelProperty(value = "Customized name of the entity")
    public String getCustomizedName() {
        return customizedName;
    }

    public void setCustomizedName(String customizedName) {
        this.customizedName = customizedName;
    }

    public ProcessGroup discoveredName(String discoveredName) {
        this.discoveredName = discoveredName;
        return this;
    }

    /**
     * Discovered name of the entity
     *
     * @return discoveredName
     **/
    @ApiModelProperty(value = "Discovered name of the entity")
    public String getDiscoveredName() {
        return discoveredName;
    }

    public void setDiscoveredName(String discoveredName) {
        this.discoveredName = discoveredName;
    }

    public ProcessGroup firstSeenTimestamp(Long firstSeenTimestamp) {
        this.firstSeenTimestamp = firstSeenTimestamp;
        return this;
    }

    /**
     * Timestamp in UTC milliseconds when the entity was detected for the first time.
     *
     * @return firstSeenTimestamp
     **/
    @ApiModelProperty(value = "Timestamp in UTC milliseconds when the entity was detected for the first time.")
    public Long getFirstSeenTimestamp() {
        return firstSeenTimestamp;
    }

    public void setFirstSeenTimestamp(Long firstSeenTimestamp) {
        this.firstSeenTimestamp = firstSeenTimestamp;
    }

    public ProcessGroup lastSeenTimestamp(Long lastSeenTimestamp) {
        this.lastSeenTimestamp = lastSeenTimestamp;
        return this;
    }

    /**
     * Timestamp in UTC milliseconds when the entity was detected for the last time.
     *
     * @return lastSeenTimestamp
     **/
    @ApiModelProperty(value = "Timestamp in UTC milliseconds when the entity was detected for the last time.")
    public Long getLastSeenTimestamp() {
        return lastSeenTimestamp;
    }

    public void setLastSeenTimestamp(Long lastSeenTimestamp) {
        this.lastSeenTimestamp = lastSeenTimestamp;
    }

    public ProcessGroup tags(List<TagInfo> tags) {
        this.tags = tags;
        return this;
    }

    public ProcessGroup addTagsItem(TagInfo tagsItem) {
        if (this.tags == null) {
            this.tags = new ArrayList<>();
        }
        this.tags.add(tagsItem);
        return this;
    }

    /**
     * The list of entity tags.
     *
     * @return tags
     **/
    @ApiModelProperty(value = "The list of entity tags.")
    public List<TagInfo> getTags() {
        return tags;
    }

    public void setTags(List<TagInfo> tags) {
        this.tags = tags;
    }

    public ProcessGroup fromRelationships(ProcessGroupFromRelationships fromRelationships) {
        this.fromRelationships = fromRelationships;
        return this;
    }

    /**
     * Get fromRelationships
     *
     * @return fromRelationships
     **/
    public ProcessGroupFromRelationships getFromRelationships() {
        return fromRelationships;
    }

    public void setFromRelationships(ProcessGroupFromRelationships fromRelationships) {
        this.fromRelationships = fromRelationships;
    }

    public ProcessGroup toRelationships(ProcessGroupToRelationships toRelationships) {
        this.toRelationships = toRelationships;
        return this;
    }

    /**
     * Get toRelationships
     *
     * @return toRelationships
     **/
    public ProcessGroupToRelationships getToRelationships() {
        return toRelationships;
    }

    public void setToRelationships(ProcessGroupToRelationships toRelationships) {
        this.toRelationships = toRelationships;
    }

    public ProcessGroup azureSiteName(List<String> azureSiteName) {
        this.azureSiteName = azureSiteName;
        return this;
    }

    public ProcessGroup addAzureSiteNameItem(String azureSiteNameItem) {
        if (this.azureSiteName == null) {
            this.azureSiteName = new ArrayList<>();
        }
        this.azureSiteName.add(azureSiteNameItem);
        return this;
    }

    /**
     * @return azureSiteName
     **/
    public List<String> getAzureSiteName() {
        return azureSiteName;
    }

    public void setAzureSiteName(List<String> azureSiteName) {
        this.azureSiteName = azureSiteName;
    }

    public ProcessGroup metadata(ProcessGroupMetadata metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get metadata
     *
     * @return metadata
     **/
    public ProcessGroupMetadata getMetadata() {
        return metadata;
    }

    public void setMetadata(ProcessGroupMetadata metadata) {
        this.metadata = metadata;
    }

    public ProcessGroup softwareTechnologies(List<TechnologyInfo> softwareTechnologies) {
        this.softwareTechnologies = softwareTechnologies;
        return this;
    }

    public ProcessGroup addSoftwareTechnologiesItem(TechnologyInfo softwareTechnologiesItem) {
        if (this.softwareTechnologies == null) {
            this.softwareTechnologies = new ArrayList<>();
        }
        this.softwareTechnologies.add(softwareTechnologiesItem);
        return this;
    }

    /**
     * @return softwareTechnologies
     **/
    public List<TechnologyInfo> getSoftwareTechnologies() {
        return softwareTechnologies;
    }

    public void setSoftwareTechnologies(List<TechnologyInfo> softwareTechnologies) {
        this.softwareTechnologies = softwareTechnologies;
    }

    public ProcessGroup azureHostName(List<String> azureHostName) {
        this.azureHostName = azureHostName;
        return this;
    }

    public ProcessGroup addAzureHostNameItem(String azureHostNameItem) {
        if (this.azureHostName == null) {
            this.azureHostName = new ArrayList<>();
        }
        this.azureHostName.add(azureHostNameItem);
        return this;
    }

    /**
     * @return azureHostName
     **/
    public List<String> getAzureHostName() {
        return azureHostName;
    }

    public void setAzureHostName(List<String> azureHostName) {
        this.azureHostName = azureHostName;
    }

    public ProcessGroup listenPorts(List<Integer> listenPorts) {
        this.listenPorts = listenPorts;
        return this;
    }

    public ProcessGroup addListenPortsItem(Integer listenPortsItem) {
        if (this.listenPorts == null) {
            this.listenPorts = new ArrayList<>();
        }
        this.listenPorts.add(listenPortsItem);
        return this;
    }

    /**
     * @return listenPorts
     **/
    public List<Integer> getListenPorts() {
        return listenPorts;
    }

    public void setListenPorts(List<Integer> listenPorts) {
        this.listenPorts = listenPorts;
    }

    @Override
    public String toString() {
        return "class ProcessGroup {\n"
                + "    entityId: " + toIndentedString(entityId) + "\n"
                + "    displayName: " + toIndentedString(displayName) + "\n"
                + "    customizedName: " + toIndentedString(customizedName) + "\n"
                + "    discoveredName: " + toIndentedString(discoveredName) + "\n"
                + "    firstSeenTimestamp: " + toIndentedString(firstSeenTimestamp) + "\n"
                + "    lastSeenTimestamp: " + toIndentedString(lastSeenTimestamp) + "\n"
                + "    tags: " + toIndentedString(tags) + "\n"
                + "    fromRelationships: " + toIndentedString(fromRelationships) + "\n"
                + "    toRelationships: " + toIndentedString(toRelationships) + "\n"
                + "    azureSiteName: " + toIndentedString(azureSiteName) + "\n"
                + "    metadata: " + toIndentedString(metadata) + "\n"
                + "    softwareTechnologies: " + toIndentedString(softwareTechnologies) + "\n"
                + "    azureHostName: " + toIndentedString(azureHostName) + "\n"
                + "    listenPorts: " + toIndentedString(listenPorts) + "\n"
                + "}";
    }
}

