/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.List;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * ProcessGroupInstanceToRelationships
 */

public class ProcessGroupInstanceToRelationships {
    @SerializedName("runsOnProcessGroupInstance")
    private List<String> runsOnProcessGroupInstance;

    @SerializedName("isNetworkClientOf")
    private List<String> isNetworkClientOf;

    public ProcessGroupInstanceToRelationships runsOnProcessGroupInstance(List<String> runsOnProcessGroupInstance) {
        this.runsOnProcessGroupInstance = runsOnProcessGroupInstance;
        return this;
    }

    public ProcessGroupInstanceToRelationships addRunsOnProcessGroupInstanceItem(String runsOnProcessGroupInstanceItem) {
        if (this.runsOnProcessGroupInstance == null) {
            this.runsOnProcessGroupInstance = new ArrayList<>();
        }
        this.runsOnProcessGroupInstance.add(runsOnProcessGroupInstanceItem);
        return this;
    }

    /**
     * @return runsOnProcessGroupInstance
     **/
    public List<String> getRunsOnProcessGroupInstance() {
        return runsOnProcessGroupInstance;
    }

    public void setRunsOnProcessGroupInstance(List<String> runsOnProcessGroupInstance) {
        this.runsOnProcessGroupInstance = runsOnProcessGroupInstance;
    }

    public ProcessGroupInstanceToRelationships isNetworkClientOf(List<String> isNetworkClientOf) {
        this.isNetworkClientOf = isNetworkClientOf;
        return this;
    }

    public ProcessGroupInstanceToRelationships addIsNetworkClientOfItem(String isNetworkClientOfItem) {
        if (this.isNetworkClientOf == null) {
            this.isNetworkClientOf = new ArrayList<>();
        }
        this.isNetworkClientOf.add(isNetworkClientOfItem);
        return this;
    }

    /**
     * @return isNetworkClientOf
     **/
    public List<String> getIsNetworkClientOf() {
        return isNetworkClientOf;
    }

    public void setIsNetworkClientOf(List<String> isNetworkClientOf) {
        this.isNetworkClientOf = isNetworkClientOf;
    }

    @Override
    public String toString() {
        return "class ProcessGroupInstanceToRelationships {\n"
                + "    runsOnProcessGroupInstance: " + toIndentedString(runsOnProcessGroupInstance) + "\n"
                + "    isNetworkClientOf: " + toIndentedString(isNetworkClientOf) + "\n"
                + "}";
    }
}

