/*
 * Copyright (c) 2014-2018 T-Systems Multimedia Solutions GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

public class ProcessGroupMetadata {
    @SerializedName("nodejsAppBaseDirectories")
    private List<String> nodejsAppBaseDirectories;

    @SerializedName("hostGroups")
    private List<String> hostGroups;

    @SerializedName("cloudFoundryAppIds")
    private List<String> cloudFoundryAppIds;

    @SerializedName("dynatraceNodeIds")
    private List<String> dynatraceNodeIds;

    @SerializedName("executables")
    private List<String> executables;

    @SerializedName("javaMainClasses")
    private List<String> javaMainClasses;

    @SerializedName("cassandraClusterNames")
    private List<String> cassandraClusterNames;

    @SerializedName("cloudFoundryAppNames")
    private List<String> cloudFoundryAppNames;

    @SerializedName("cloudFoundrySpaceNames")
    private List<String> cloudFoundrySpaceNames;

    @SerializedName("phpScripts")
    private List<String> phpScripts;

    @SerializedName("pluginMetadata")
    private Map<String, String> pluginMetadata;

    @SerializedName("dockerContainerNames")
    private List<String> dockerContainerNames;

    @SerializedName("glassfishInstanceNames")
    private List<String> glassfishInstanceNames;

    @SerializedName("tibcoBusinessWorksEnginePropertyFiles")
    private List<String> tibcoBusinessWorksEnginePropertyFiles;

    @SerializedName("jbossServerNames")
    private List<String> jbossServerNames;

    @SerializedName("catalinaBaseValues")
    private List<String> catalinaBaseValues;

    @SerializedName("kubernetesFullPodNames")
    private List<String> kubernetesFullPodNames;

    @SerializedName("apacheConfigPaths")
    private List<String> apacheConfigPaths;

    @SerializedName("varnishInstanceNames")
    private List<String> varnishInstanceNames;

    @SerializedName("phpWorkingDirectories")
    private List<String> phpWorkingDirectories;

    @SerializedName("googleCloudProjects")
    private List<String> googleCloudProjects;

    @SerializedName("dockerContainerImageVersions")
    private List<String> dockerContainerImageVersions;

    @SerializedName("hybrisConfigDirectories")
    private List<String> hybrisConfigDirectories;

    @SerializedName("executablePaths")
    private List<String> executablePaths;

    @SerializedName("awsEcrImageRegions")
    private List<String> awsEcrImageRegions;

    @SerializedName("dotNetCommands")
    private List<String> dotNetCommands;

    @SerializedName("weblogicDomainNames")
    private List<String> weblogicDomainNames;

    @SerializedName("googleAppEngineServices")
    private List<String> googleAppEngineServices;

    @SerializedName("ibmIntegrationBusBrokerNames")
    private List<String> ibmIntegrationBusBrokerNames;

    @SerializedName("elasticSearchNodeNames")
    private List<String> elasticSearchNodeNames;

    @SerializedName("kubernetesNamespaces")
    private List<String> kubernetesNamespaces;

    @SerializedName("hybrisDataDirectories")
    private List<String> hybrisDataDirectories;

    @SerializedName("envVariables")
    private Map<String, String> envVariables;

    @SerializedName("javaJarFiles")
    private List<String> javaJarFiles;

    @SerializedName("javaJarPaths")
    private List<String> javaJarPaths;

    @SerializedName("dockerContainerIds")
    private List<String> dockerContainerIds;

    @SerializedName("cloudFoundrySpaceIds")
    private List<String> cloudFoundrySpaceIds;

    @SerializedName("tibcoBWEnginePropertyFilePaths")
    private List<String> tibcoBWEnginePropertyFilePaths;

    @SerializedName("kubernetesContainerNames")
    private List<String> kubernetesContainerNames;

    @SerializedName("ruleResult")
    private List<String> ruleResult;

    @SerializedName("rubyAppRootPaths")
    private List<String> rubyAppRootPaths;

    @SerializedName("jbossModes")
    private List<String> jbossModes;

    @SerializedName("awsLambdaFunctionNames")
    private List<String> awsLambdaFunctionNames;

    @SerializedName("cloudFoundryInstanceIndexes")
    private List<String> cloudFoundryInstanceIndexes;

    @SerializedName("hybrisBinDirectories")
    private List<String> hybrisBinDirectories;

    @SerializedName("weblogicHomeValues")
    private List<String> weblogicHomeValues;

    @SerializedName("jbossHomes")
    private List<String> jbossHomes;

    @SerializedName("dynatraceClusterIds")
    private List<String> dynatraceClusterIds;

    @SerializedName("googleAppEngineInstances")
    private List<String> googleAppEngineInstances;

    @SerializedName("commandLineArgs")
    private List<String> commandLineArgs;

    @SerializedName("aspDotNetCoreApplicationPaths")
    private List<String> aspDotNetCoreApplicationPaths;

    @SerializedName("awsEcrImageAccountIds")
    private List<String> awsEcrImageAccountIds;

    @SerializedName("websphereClusterNames")
    private List<String> websphereClusterNames;

    @SerializedName("kubernetesAnnotations")
    private Map<String, String> kubernetesAnnotations;

    @SerializedName("websphereServerNames")
    private List<String> websphereServerNames;

    @SerializedName("catalinaHomeValues")
    private List<String> catalinaHomeValues;

    @SerializedName("glassfishDomainNames")
    private List<String> glassfishDomainNames;

    @SerializedName("kubernetesBasePodNames")
    private List<String> kubernetesBasePodNames;

    @SerializedName("weblogicClusterNames")
    private List<String> weblogicClusterNames;

    @SerializedName("websphereNodeNames")
    private List<String> websphereNodeNames;

    @SerializedName("iisAppPools")
    private List<String> iisAppPools;

    @SerializedName("javaMainModules")
    private List<String> javaMainModules;

    @SerializedName("kubernetesPodUids")
    private List<String> kubernetesPodUids;

    @SerializedName("dockerContainerImageNames")
    private List<String> dockerContainerImageNames;

    @SerializedName("coldfusionJvmConfigFiles")
    private List<String> coldfusionJvmConfigFiles;

    @SerializedName("serviceNames")
    private List<String> serviceNames;

    @SerializedName("dotnetCommandPath")
    private List<String> dotnetCommandPath;

    @SerializedName("ibmIntegrationBusExecutionGroupNames")
    private List<String> ibmIntegrationBusExecutionGroupNames;

    @SerializedName("websphereCellNames")
    private List<String> websphereCellNames;

    @SerializedName("elasticSearchClusterNames")
    private List<String> elasticSearchClusterNames;

    @SerializedName("nodejsAppNames")
    private List<String> nodejsAppNames;

    @SerializedName("nodejsScriptNames")
    private List<String> nodejsScriptNames;

    @SerializedName("iisRoleNames")
    private List<String> iisRoleNames;

    @SerializedName("apacheSparkMasterIpAddresses")
    private List<String> apacheSparkMasterIpAddresses;

    @SerializedName("weblogicNames")
    private List<String> weblogicNames;

    @SerializedName("rubyScriptPaths")
    private List<String> rubyScriptPaths;

    @SerializedName("awsRegions")
    private List<String> awsRegions;

    public ProcessGroupMetadata nodejsAppBaseDirectories(List<String> nodejsAppBaseDirectories) {
        this.nodejsAppBaseDirectories = nodejsAppBaseDirectories;
        return this;
    }

    public ProcessGroupMetadata addNodejsAppBaseDirectoriesItem(String nodejsAppBaseDirectoriesItem) {
        if (this.nodejsAppBaseDirectories == null) {
            this.nodejsAppBaseDirectories = new ArrayList<>();
        }
        this.nodejsAppBaseDirectories.add(nodejsAppBaseDirectoriesItem);
        return this;
    }

    /**
     * @return nodejsAppBaseDirectories
     **/
    public List<String> getNodejsAppBaseDirectories() {
        return nodejsAppBaseDirectories;
    }

    public void setNodejsAppBaseDirectories(List<String> nodejsAppBaseDirectories) {
        this.nodejsAppBaseDirectories = nodejsAppBaseDirectories;
    }

    public ProcessGroupMetadata hostGroups(List<String> hostGroups) {
        this.hostGroups = hostGroups;
        return this;
    }

    public ProcessGroupMetadata addHostGroupsItem(String hostGroupsItem) {
        if (this.hostGroups == null) {
            this.hostGroups = new ArrayList<>();
        }
        this.hostGroups.add(hostGroupsItem);
        return this;
    }

    /**
     * @return hostGroups
     **/
    public List<String> getHostGroups() {
        return hostGroups;
    }

    public void setHostGroups(List<String> hostGroups) {
        this.hostGroups = hostGroups;
    }

    public ProcessGroupMetadata cloudFoundryAppIds(List<String> cloudFoundryAppIds) {
        this.cloudFoundryAppIds = cloudFoundryAppIds;
        return this;
    }

    public ProcessGroupMetadata addCloudFoundryAppIdsItem(String cloudFoundryAppIdsItem) {
        if (this.cloudFoundryAppIds == null) {
            this.cloudFoundryAppIds = new ArrayList<>();
        }
        this.cloudFoundryAppIds.add(cloudFoundryAppIdsItem);
        return this;
    }

    /**
     * @return cloudFoundryAppIds
     **/
    public List<String> getCloudFoundryAppIds() {
        return cloudFoundryAppIds;
    }

    public void setCloudFoundryAppIds(List<String> cloudFoundryAppIds) {
        this.cloudFoundryAppIds = cloudFoundryAppIds;
    }

    public ProcessGroupMetadata dynatraceNodeIds(List<String> dynatraceNodeIds) {
        this.dynatraceNodeIds = dynatraceNodeIds;
        return this;
    }

    public ProcessGroupMetadata addDynatraceNodeIdsItem(String dynatraceNodeIdsItem) {
        if (this.dynatraceNodeIds == null) {
            this.dynatraceNodeIds = new ArrayList<>();
        }
        this.dynatraceNodeIds.add(dynatraceNodeIdsItem);
        return this;
    }

    /**
     * @return dynatraceNodeIds
     **/
    public List<String> getDynatraceNodeIds() {
        return dynatraceNodeIds;
    }

    public void setDynatraceNodeIds(List<String> dynatraceNodeIds) {
        this.dynatraceNodeIds = dynatraceNodeIds;
    }

    public ProcessGroupMetadata executables(List<String> executables) {
        this.executables = executables;
        return this;
    }

    public ProcessGroupMetadata addExecutablesItem(String executablesItem) {
        if (this.executables == null) {
            this.executables = new ArrayList<>();
        }
        this.executables.add(executablesItem);
        return this;
    }

    /**
     * @return executables
     **/
    public List<String> getExecutables() {
        return executables;
    }

    public void setExecutables(List<String> executables) {
        this.executables = executables;
    }

    public ProcessGroupMetadata javaMainClasses(List<String> javaMainClasses) {
        this.javaMainClasses = javaMainClasses;
        return this;
    }

    public ProcessGroupMetadata addJavaMainClassesItem(String javaMainClassesItem) {
        if (this.javaMainClasses == null) {
            this.javaMainClasses = new ArrayList<>();
        }
        this.javaMainClasses.add(javaMainClassesItem);
        return this;
    }

    /**
     * @return javaMainClasses
     **/
    public List<String> getJavaMainClasses() {
        return javaMainClasses;
    }

    public void setJavaMainClasses(List<String> javaMainClasses) {
        this.javaMainClasses = javaMainClasses;
    }

    public ProcessGroupMetadata cassandraClusterNames(List<String> cassandraClusterNames) {
        this.cassandraClusterNames = cassandraClusterNames;
        return this;
    }

    public ProcessGroupMetadata addCassandraClusterNamesItem(String cassandraClusterNamesItem) {
        if (this.cassandraClusterNames == null) {
            this.cassandraClusterNames = new ArrayList<>();
        }
        this.cassandraClusterNames.add(cassandraClusterNamesItem);
        return this;
    }

    /**
     * @return cassandraClusterNames
     **/
    public List<String> getCassandraClusterNames() {
        return cassandraClusterNames;
    }

    public void setCassandraClusterNames(List<String> cassandraClusterNames) {
        this.cassandraClusterNames = cassandraClusterNames;
    }

    public ProcessGroupMetadata cloudFoundryAppNames(List<String> cloudFoundryAppNames) {
        this.cloudFoundryAppNames = cloudFoundryAppNames;
        return this;
    }

    public ProcessGroupMetadata addCloudFoundryAppNamesItem(String cloudFoundryAppNamesItem) {
        if (this.cloudFoundryAppNames == null) {
            this.cloudFoundryAppNames = new ArrayList<>();
        }
        this.cloudFoundryAppNames.add(cloudFoundryAppNamesItem);
        return this;
    }

    /**
     * @return cloudFoundryAppNames
     **/
    public List<String> getCloudFoundryAppNames() {
        return cloudFoundryAppNames;
    }

    public void setCloudFoundryAppNames(List<String> cloudFoundryAppNames) {
        this.cloudFoundryAppNames = cloudFoundryAppNames;
    }

    public ProcessGroupMetadata cloudFoundrySpaceNames(List<String> cloudFoundrySpaceNames) {
        this.cloudFoundrySpaceNames = cloudFoundrySpaceNames;
        return this;
    }

    public ProcessGroupMetadata addCloudFoundrySpaceNamesItem(String cloudFoundrySpaceNamesItem) {
        if (this.cloudFoundrySpaceNames == null) {
            this.cloudFoundrySpaceNames = new ArrayList<>();
        }
        this.cloudFoundrySpaceNames.add(cloudFoundrySpaceNamesItem);
        return this;
    }

    /**
     * @return cloudFoundrySpaceNames
     **/
    public List<String> getCloudFoundrySpaceNames() {
        return cloudFoundrySpaceNames;
    }

    public void setCloudFoundrySpaceNames(List<String> cloudFoundrySpaceNames) {
        this.cloudFoundrySpaceNames = cloudFoundrySpaceNames;
    }

    public ProcessGroupMetadata phpScripts(List<String> phpScripts) {
        this.phpScripts = phpScripts;
        return this;
    }

    public ProcessGroupMetadata addPhpScriptsItem(String phpScriptsItem) {
        if (this.phpScripts == null) {
            this.phpScripts = new ArrayList<>();
        }
        this.phpScripts.add(phpScriptsItem);
        return this;
    }

    /**
     * @return phpScripts
     **/
    public List<String> getPhpScripts() {
        return phpScripts;
    }

    public void setPhpScripts(List<String> phpScripts) {
        this.phpScripts = phpScripts;
    }

    public ProcessGroupMetadata pluginMetadata(Map<String, String> pluginMetadata) {
        this.pluginMetadata = pluginMetadata;
        return this;
    }

    public ProcessGroupMetadata putPluginMetadataItem(String key, String pluginMetadataItem) {
        if (this.pluginMetadata == null) {
            this.pluginMetadata = new HashMap<>();
        }
        this.pluginMetadata.put(key, pluginMetadataItem);
        return this;
    }

    /**
     * @return pluginMetadata
     **/
    public Map<String, String> getPluginMetadata() {
        return pluginMetadata;
    }

    public void setPluginMetadata(Map<String, String> pluginMetadata) {
        this.pluginMetadata = pluginMetadata;
    }

    public ProcessGroupMetadata dockerContainerNames(List<String> dockerContainerNames) {
        this.dockerContainerNames = dockerContainerNames;
        return this;
    }

    public ProcessGroupMetadata addDockerContainerNamesItem(String dockerContainerNamesItem) {
        if (this.dockerContainerNames == null) {
            this.dockerContainerNames = new ArrayList<>();
        }
        this.dockerContainerNames.add(dockerContainerNamesItem);
        return this;
    }

    /**
     * @return dockerContainerNames
     **/
    public List<String> getDockerContainerNames() {
        return dockerContainerNames;
    }

    public void setDockerContainerNames(List<String> dockerContainerNames) {
        this.dockerContainerNames = dockerContainerNames;
    }

    public ProcessGroupMetadata glassfishInstanceNames(List<String> glassfishInstanceNames) {
        this.glassfishInstanceNames = glassfishInstanceNames;
        return this;
    }

    public ProcessGroupMetadata addGlassfishInstanceNamesItem(String glassfishInstanceNamesItem) {
        if (this.glassfishInstanceNames == null) {
            this.glassfishInstanceNames = new ArrayList<>();
        }
        this.glassfishInstanceNames.add(glassfishInstanceNamesItem);
        return this;
    }

    /**
     * @return glassfishInstanceNames
     **/
    public List<String> getGlassfishInstanceNames() {
        return glassfishInstanceNames;
    }

    public void setGlassfishInstanceNames(List<String> glassfishInstanceNames) {
        this.glassfishInstanceNames = glassfishInstanceNames;
    }

    public ProcessGroupMetadata tibcoBusinessWorksEnginePropertyFiles(List<String> tibcoBusinessWorksEnginePropertyFiles) {
        this.tibcoBusinessWorksEnginePropertyFiles = tibcoBusinessWorksEnginePropertyFiles;
        return this;
    }

    public ProcessGroupMetadata addTibcoBusinessWorksEnginePropertyFilesItem(String tibcoBusinessWorksEnginePropertyFilesItem) {
        if (this.tibcoBusinessWorksEnginePropertyFiles == null) {
            this.tibcoBusinessWorksEnginePropertyFiles = new ArrayList<>();
        }
        this.tibcoBusinessWorksEnginePropertyFiles.add(tibcoBusinessWorksEnginePropertyFilesItem);
        return this;
    }

    /**
     * @return tibcoBusinessWorksEnginePropertyFiles
     **/
    public List<String> getTibcoBusinessWorksEnginePropertyFiles() {
        return tibcoBusinessWorksEnginePropertyFiles;
    }

    public void setTibcoBusinessWorksEnginePropertyFiles(List<String> tibcoBusinessWorksEnginePropertyFiles) {
        this.tibcoBusinessWorksEnginePropertyFiles = tibcoBusinessWorksEnginePropertyFiles;
    }

    public ProcessGroupMetadata jbossServerNames(List<String> jbossServerNames) {
        this.jbossServerNames = jbossServerNames;
        return this;
    }

    public ProcessGroupMetadata addJbossServerNamesItem(String jbossServerNamesItem) {
        if (this.jbossServerNames == null) {
            this.jbossServerNames = new ArrayList<>();
        }
        this.jbossServerNames.add(jbossServerNamesItem);
        return this;
    }

    /**
     * @return jbossServerNames
     **/
    public List<String> getJbossServerNames() {
        return jbossServerNames;
    }

    public void setJbossServerNames(List<String> jbossServerNames) {
        this.jbossServerNames = jbossServerNames;
    }

    public ProcessGroupMetadata catalinaBaseValues(List<String> catalinaBaseValues) {
        this.catalinaBaseValues = catalinaBaseValues;
        return this;
    }

    public ProcessGroupMetadata addCatalinaBaseValuesItem(String catalinaBaseValuesItem) {
        if (this.catalinaBaseValues == null) {
            this.catalinaBaseValues = new ArrayList<>();
        }
        this.catalinaBaseValues.add(catalinaBaseValuesItem);
        return this;
    }

    /**
     * @return catalinaBaseValues
     **/
    public List<String> getCatalinaBaseValues() {
        return catalinaBaseValues;
    }

    public void setCatalinaBaseValues(List<String> catalinaBaseValues) {
        this.catalinaBaseValues = catalinaBaseValues;
    }

    public ProcessGroupMetadata kubernetesFullPodNames(List<String> kubernetesFullPodNames) {
        this.kubernetesFullPodNames = kubernetesFullPodNames;
        return this;
    }

    public ProcessGroupMetadata addKubernetesFullPodNamesItem(String kubernetesFullPodNamesItem) {
        if (this.kubernetesFullPodNames == null) {
            this.kubernetesFullPodNames = new ArrayList<>();
        }
        this.kubernetesFullPodNames.add(kubernetesFullPodNamesItem);
        return this;
    }

    /**
     * @return kubernetesFullPodNames
     **/
    public List<String> getKubernetesFullPodNames() {
        return kubernetesFullPodNames;
    }

    public void setKubernetesFullPodNames(List<String> kubernetesFullPodNames) {
        this.kubernetesFullPodNames = kubernetesFullPodNames;
    }

    public ProcessGroupMetadata apacheConfigPaths(List<String> apacheConfigPaths) {
        this.apacheConfigPaths = apacheConfigPaths;
        return this;
    }

    public ProcessGroupMetadata addApacheConfigPathsItem(String apacheConfigPathsItem) {
        if (this.apacheConfigPaths == null) {
            this.apacheConfigPaths = new ArrayList<>();
        }
        this.apacheConfigPaths.add(apacheConfigPathsItem);
        return this;
    }

    /**
     * @return apacheConfigPaths
     **/
    public List<String> getApacheConfigPaths() {
        return apacheConfigPaths;
    }

    public void setApacheConfigPaths(List<String> apacheConfigPaths) {
        this.apacheConfigPaths = apacheConfigPaths;
    }

    public ProcessGroupMetadata varnishInstanceNames(List<String> varnishInstanceNames) {
        this.varnishInstanceNames = varnishInstanceNames;
        return this;
    }

    public ProcessGroupMetadata addVarnishInstanceNamesItem(String varnishInstanceNamesItem) {
        if (this.varnishInstanceNames == null) {
            this.varnishInstanceNames = new ArrayList<>();
        }
        this.varnishInstanceNames.add(varnishInstanceNamesItem);
        return this;
    }

    /**
     * @return varnishInstanceNames
     **/
    public List<String> getVarnishInstanceNames() {
        return varnishInstanceNames;
    }

    public void setVarnishInstanceNames(List<String> varnishInstanceNames) {
        this.varnishInstanceNames = varnishInstanceNames;
    }

    public ProcessGroupMetadata phpWorkingDirectories(List<String> phpWorkingDirectories) {
        this.phpWorkingDirectories = phpWorkingDirectories;
        return this;
    }

    public ProcessGroupMetadata addPhpWorkingDirectoriesItem(String phpWorkingDirectoriesItem) {
        if (this.phpWorkingDirectories == null) {
            this.phpWorkingDirectories = new ArrayList<>();
        }
        this.phpWorkingDirectories.add(phpWorkingDirectoriesItem);
        return this;
    }

    /**
     * @return phpWorkingDirectories
     **/
    public List<String> getPhpWorkingDirectories() {
        return phpWorkingDirectories;
    }

    public void setPhpWorkingDirectories(List<String> phpWorkingDirectories) {
        this.phpWorkingDirectories = phpWorkingDirectories;
    }

    public ProcessGroupMetadata googleCloudProjects(List<String> googleCloudProjects) {
        this.googleCloudProjects = googleCloudProjects;
        return this;
    }

    public ProcessGroupMetadata addGoogleCloudProjectsItem(String googleCloudProjectsItem) {
        if (this.googleCloudProjects == null) {
            this.googleCloudProjects = new ArrayList<>();
        }
        this.googleCloudProjects.add(googleCloudProjectsItem);
        return this;
    }

    /**
     * @return googleCloudProjects
     **/
    public List<String> getGoogleCloudProjects() {
        return googleCloudProjects;
    }

    public void setGoogleCloudProjects(List<String> googleCloudProjects) {
        this.googleCloudProjects = googleCloudProjects;
    }

    public ProcessGroupMetadata dockerContainerImageVersions(List<String> dockerContainerImageVersions) {
        this.dockerContainerImageVersions = dockerContainerImageVersions;
        return this;
    }

    public ProcessGroupMetadata addDockerContainerImageVersionsItem(String dockerContainerImageVersionsItem) {
        if (this.dockerContainerImageVersions == null) {
            this.dockerContainerImageVersions = new ArrayList<>();
        }
        this.dockerContainerImageVersions.add(dockerContainerImageVersionsItem);
        return this;
    }

    /**
     * @return dockerContainerImageVersions
     **/
    public List<String> getDockerContainerImageVersions() {
        return dockerContainerImageVersions;
    }

    public void setDockerContainerImageVersions(List<String> dockerContainerImageVersions) {
        this.dockerContainerImageVersions = dockerContainerImageVersions;
    }

    public ProcessGroupMetadata hybrisConfigDirectories(List<String> hybrisConfigDirectories) {
        this.hybrisConfigDirectories = hybrisConfigDirectories;
        return this;
    }

    public ProcessGroupMetadata addHybrisConfigDirectoriesItem(String hybrisConfigDirectoriesItem) {
        if (this.hybrisConfigDirectories == null) {
            this.hybrisConfigDirectories = new ArrayList<>();
        }
        this.hybrisConfigDirectories.add(hybrisConfigDirectoriesItem);
        return this;
    }

    /**
     * @return hybrisConfigDirectories
     **/
    public List<String> getHybrisConfigDirectories() {
        return hybrisConfigDirectories;
    }

    public void setHybrisConfigDirectories(List<String> hybrisConfigDirectories) {
        this.hybrisConfigDirectories = hybrisConfigDirectories;
    }

    public ProcessGroupMetadata executablePaths(List<String> executablePaths) {
        this.executablePaths = executablePaths;
        return this;
    }

    public ProcessGroupMetadata addExecutablePathsItem(String executablePathsItem) {
        if (this.executablePaths == null) {
            this.executablePaths = new ArrayList<>();
        }
        this.executablePaths.add(executablePathsItem);
        return this;
    }

    /**
     * @return executablePaths
     **/
    public List<String> getExecutablePaths() {
        return executablePaths;
    }

    public void setExecutablePaths(List<String> executablePaths) {
        this.executablePaths = executablePaths;
    }

    public ProcessGroupMetadata awsEcrImageRegions(List<String> awsEcrImageRegions) {
        this.awsEcrImageRegions = awsEcrImageRegions;
        return this;
    }

    public ProcessGroupMetadata addAwsEcrImageRegionsItem(String awsEcrImageRegionsItem) {
        if (this.awsEcrImageRegions == null) {
            this.awsEcrImageRegions = new ArrayList<>();
        }
        this.awsEcrImageRegions.add(awsEcrImageRegionsItem);
        return this;
    }

    /**
     * @return awsEcrImageRegions
     **/
    public List<String> getAwsEcrImageRegions() {
        return awsEcrImageRegions;
    }

    public void setAwsEcrImageRegions(List<String> awsEcrImageRegions) {
        this.awsEcrImageRegions = awsEcrImageRegions;
    }

    public ProcessGroupMetadata dotNetCommands(List<String> dotNetCommands) {
        this.dotNetCommands = dotNetCommands;
        return this;
    }

    public ProcessGroupMetadata addDotNetCommandsItem(String dotNetCommandsItem) {
        if (this.dotNetCommands == null) {
            this.dotNetCommands = new ArrayList<>();
        }
        this.dotNetCommands.add(dotNetCommandsItem);
        return this;
    }

    /**
     * @return dotNetCommands
     **/
    public List<String> getDotNetCommands() {
        return dotNetCommands;
    }

    public void setDotNetCommands(List<String> dotNetCommands) {
        this.dotNetCommands = dotNetCommands;
    }

    public ProcessGroupMetadata weblogicDomainNames(List<String> weblogicDomainNames) {
        this.weblogicDomainNames = weblogicDomainNames;
        return this;
    }

    public ProcessGroupMetadata addWeblogicDomainNamesItem(String weblogicDomainNamesItem) {
        if (this.weblogicDomainNames == null) {
            this.weblogicDomainNames = new ArrayList<>();
        }
        this.weblogicDomainNames.add(weblogicDomainNamesItem);
        return this;
    }

    /**
     * @return weblogicDomainNames
     **/
    public List<String> getWeblogicDomainNames() {
        return weblogicDomainNames;
    }

    public void setWeblogicDomainNames(List<String> weblogicDomainNames) {
        this.weblogicDomainNames = weblogicDomainNames;
    }

    public ProcessGroupMetadata googleAppEngineServices(List<String> googleAppEngineServices) {
        this.googleAppEngineServices = googleAppEngineServices;
        return this;
    }

    public ProcessGroupMetadata addGoogleAppEngineServicesItem(String googleAppEngineServicesItem) {
        if (this.googleAppEngineServices == null) {
            this.googleAppEngineServices = new ArrayList<>();
        }
        this.googleAppEngineServices.add(googleAppEngineServicesItem);
        return this;
    }

    /**
     * @return googleAppEngineServices
     **/
    public List<String> getGoogleAppEngineServices() {
        return googleAppEngineServices;
    }

    public void setGoogleAppEngineServices(List<String> googleAppEngineServices) {
        this.googleAppEngineServices = googleAppEngineServices;
    }

    public ProcessGroupMetadata ibmIntegrationBusBrokerNames(List<String> ibmIntegrationBusBrokerNames) {
        this.ibmIntegrationBusBrokerNames = ibmIntegrationBusBrokerNames;
        return this;
    }

    public ProcessGroupMetadata addIbmIntegrationBusBrokerNamesItem(String ibmIntegrationBusBrokerNamesItem) {
        if (this.ibmIntegrationBusBrokerNames == null) {
            this.ibmIntegrationBusBrokerNames = new ArrayList<>();
        }
        this.ibmIntegrationBusBrokerNames.add(ibmIntegrationBusBrokerNamesItem);
        return this;
    }

    /**
     * @return ibmIntegrationBusBrokerNames
     **/
    public List<String> getIbmIntegrationBusBrokerNames() {
        return ibmIntegrationBusBrokerNames;
    }

    public void setIbmIntegrationBusBrokerNames(List<String> ibmIntegrationBusBrokerNames) {
        this.ibmIntegrationBusBrokerNames = ibmIntegrationBusBrokerNames;
    }

    public ProcessGroupMetadata elasticSearchNodeNames(List<String> elasticSearchNodeNames) {
        this.elasticSearchNodeNames = elasticSearchNodeNames;
        return this;
    }

    public ProcessGroupMetadata addElasticSearchNodeNamesItem(String elasticSearchNodeNamesItem) {
        if (this.elasticSearchNodeNames == null) {
            this.elasticSearchNodeNames = new ArrayList<>();
        }
        this.elasticSearchNodeNames.add(elasticSearchNodeNamesItem);
        return this;
    }

    /**
     * @return elasticSearchNodeNames
     **/
    public List<String> getElasticSearchNodeNames() {
        return elasticSearchNodeNames;
    }

    public void setElasticSearchNodeNames(List<String> elasticSearchNodeNames) {
        this.elasticSearchNodeNames = elasticSearchNodeNames;
    }

    public ProcessGroupMetadata kubernetesNamespaces(List<String> kubernetesNamespaces) {
        this.kubernetesNamespaces = kubernetesNamespaces;
        return this;
    }

    public ProcessGroupMetadata addKubernetesNamespacesItem(String kubernetesNamespacesItem) {
        if (this.kubernetesNamespaces == null) {
            this.kubernetesNamespaces = new ArrayList<>();
        }
        this.kubernetesNamespaces.add(kubernetesNamespacesItem);
        return this;
    }

    /**
     * @return kubernetesNamespaces
     **/
    public List<String> getKubernetesNamespaces() {
        return kubernetesNamespaces;
    }

    public void setKubernetesNamespaces(List<String> kubernetesNamespaces) {
        this.kubernetesNamespaces = kubernetesNamespaces;
    }

    public ProcessGroupMetadata hybrisDataDirectories(List<String> hybrisDataDirectories) {
        this.hybrisDataDirectories = hybrisDataDirectories;
        return this;
    }

    public ProcessGroupMetadata addHybrisDataDirectoriesItem(String hybrisDataDirectoriesItem) {
        if (this.hybrisDataDirectories == null) {
            this.hybrisDataDirectories = new ArrayList<>();
        }
        this.hybrisDataDirectories.add(hybrisDataDirectoriesItem);
        return this;
    }

    /**
     * @return hybrisDataDirectories
     **/
    public List<String> getHybrisDataDirectories() {
        return hybrisDataDirectories;
    }

    public void setHybrisDataDirectories(List<String> hybrisDataDirectories) {
        this.hybrisDataDirectories = hybrisDataDirectories;
    }

    public ProcessGroupMetadata envVariables(Map<String, String> envVariables) {
        this.envVariables = envVariables;
        return this;
    }

    public ProcessGroupMetadata putEnvVariablesItem(String key, String envVariablesItem) {
        if (this.envVariables == null) {
            this.envVariables = new HashMap<>();
        }
        this.envVariables.put(key, envVariablesItem);
        return this;
    }

    /**
     * @return envVariables
     **/
    public Map<String, String> getEnvVariables() {
        return envVariables;
    }

    public void setEnvVariables(Map<String, String> envVariables) {
        this.envVariables = envVariables;
    }

    public ProcessGroupMetadata javaJarFiles(List<String> javaJarFiles) {
        this.javaJarFiles = javaJarFiles;
        return this;
    }

    public ProcessGroupMetadata addJavaJarFilesItem(String javaJarFilesItem) {
        if (this.javaJarFiles == null) {
            this.javaJarFiles = new ArrayList<>();
        }
        this.javaJarFiles.add(javaJarFilesItem);
        return this;
    }

    /**
     * @return javaJarFiles
     **/
    public List<String> getJavaJarFiles() {
        return javaJarFiles;
    }

    public void setJavaJarFiles(List<String> javaJarFiles) {
        this.javaJarFiles = javaJarFiles;
    }

    public ProcessGroupMetadata javaJarPaths(List<String> javaJarPaths) {
        this.javaJarPaths = javaJarPaths;
        return this;
    }

    public ProcessGroupMetadata addJavaJarPathsItem(String javaJarPathsItem) {
        if (this.javaJarPaths == null) {
            this.javaJarPaths = new ArrayList<>();
        }
        this.javaJarPaths.add(javaJarPathsItem);
        return this;
    }

    /**
     * @return javaJarPaths
     **/
    public List<String> getJavaJarPaths() {
        return javaJarPaths;
    }

    public void setJavaJarPaths(List<String> javaJarPaths) {
        this.javaJarPaths = javaJarPaths;
    }

    public ProcessGroupMetadata dockerContainerIds(List<String> dockerContainerIds) {
        this.dockerContainerIds = dockerContainerIds;
        return this;
    }

    public ProcessGroupMetadata addDockerContainerIdsItem(String dockerContainerIdsItem) {
        if (this.dockerContainerIds == null) {
            this.dockerContainerIds = new ArrayList<>();
        }
        this.dockerContainerIds.add(dockerContainerIdsItem);
        return this;
    }

    /**
     * @return dockerContainerIds
     **/
    public List<String> getDockerContainerIds() {
        return dockerContainerIds;
    }

    public void setDockerContainerIds(List<String> dockerContainerIds) {
        this.dockerContainerIds = dockerContainerIds;
    }

    public ProcessGroupMetadata cloudFoundrySpaceIds(List<String> cloudFoundrySpaceIds) {
        this.cloudFoundrySpaceIds = cloudFoundrySpaceIds;
        return this;
    }

    public ProcessGroupMetadata addCloudFoundrySpaceIdsItem(String cloudFoundrySpaceIdsItem) {
        if (this.cloudFoundrySpaceIds == null) {
            this.cloudFoundrySpaceIds = new ArrayList<>();
        }
        this.cloudFoundrySpaceIds.add(cloudFoundrySpaceIdsItem);
        return this;
    }

    /**
     * @return cloudFoundrySpaceIds
     **/
    public List<String> getCloudFoundrySpaceIds() {
        return cloudFoundrySpaceIds;
    }

    public void setCloudFoundrySpaceIds(List<String> cloudFoundrySpaceIds) {
        this.cloudFoundrySpaceIds = cloudFoundrySpaceIds;
    }

    public ProcessGroupMetadata tibcoBWEnginePropertyFilePaths(List<String> tibcoBWEnginePropertyFilePaths) {
        this.tibcoBWEnginePropertyFilePaths = tibcoBWEnginePropertyFilePaths;
        return this;
    }

    public ProcessGroupMetadata addTibcoBWEnginePropertyFilePathsItem(String tibcoBWEnginePropertyFilePathsItem) {
        if (this.tibcoBWEnginePropertyFilePaths == null) {
            this.tibcoBWEnginePropertyFilePaths = new ArrayList<>();
        }
        this.tibcoBWEnginePropertyFilePaths.add(tibcoBWEnginePropertyFilePathsItem);
        return this;
    }

    /**
     * @return tibcoBWEnginePropertyFilePaths
     **/
    public List<String> getTibcoBWEnginePropertyFilePaths() {
        return tibcoBWEnginePropertyFilePaths;
    }

    public void setTibcoBWEnginePropertyFilePaths(List<String> tibcoBWEnginePropertyFilePaths) {
        this.tibcoBWEnginePropertyFilePaths = tibcoBWEnginePropertyFilePaths;
    }

    public ProcessGroupMetadata kubernetesContainerNames(List<String> kubernetesContainerNames) {
        this.kubernetesContainerNames = kubernetesContainerNames;
        return this;
    }

    public ProcessGroupMetadata addKubernetesContainerNamesItem(String kubernetesContainerNamesItem) {
        if (this.kubernetesContainerNames == null) {
            this.kubernetesContainerNames = new ArrayList<>();
        }
        this.kubernetesContainerNames.add(kubernetesContainerNamesItem);
        return this;
    }

    /**
     * @return kubernetesContainerNames
     **/
    public List<String> getKubernetesContainerNames() {
        return kubernetesContainerNames;
    }

    public void setKubernetesContainerNames(List<String> kubernetesContainerNames) {
        this.kubernetesContainerNames = kubernetesContainerNames;
    }

    public ProcessGroupMetadata ruleResult(List<String> ruleResult) {
        this.ruleResult = ruleResult;
        return this;
    }

    public ProcessGroupMetadata addRuleResultItem(String ruleResultItem) {
        if (this.ruleResult == null) {
            this.ruleResult = new ArrayList<>();
        }
        this.ruleResult.add(ruleResultItem);
        return this;
    }

    /**
     * @return ruleResult
     **/
    public List<String> getRuleResult() {
        return ruleResult;
    }

    public void setRuleResult(List<String> ruleResult) {
        this.ruleResult = ruleResult;
    }

    public ProcessGroupMetadata rubyAppRootPaths(List<String> rubyAppRootPaths) {
        this.rubyAppRootPaths = rubyAppRootPaths;
        return this;
    }

    public ProcessGroupMetadata addRubyAppRootPathsItem(String rubyAppRootPathsItem) {
        if (this.rubyAppRootPaths == null) {
            this.rubyAppRootPaths = new ArrayList<>();
        }
        this.rubyAppRootPaths.add(rubyAppRootPathsItem);
        return this;
    }

    /**
     * @return rubyAppRootPaths
     **/
    public List<String> getRubyAppRootPaths() {
        return rubyAppRootPaths;
    }

    public void setRubyAppRootPaths(List<String> rubyAppRootPaths) {
        this.rubyAppRootPaths = rubyAppRootPaths;
    }

    public ProcessGroupMetadata jbossModes(List<String> jbossModes) {
        this.jbossModes = jbossModes;
        return this;
    }

    public ProcessGroupMetadata addJbossModesItem(String jbossModesItem) {
        if (this.jbossModes == null) {
            this.jbossModes = new ArrayList<>();
        }
        this.jbossModes.add(jbossModesItem);
        return this;
    }

    /**
     * @return jbossModes
     **/
    public List<String> getJbossModes() {
        return jbossModes;
    }

    public void setJbossModes(List<String> jbossModes) {
        this.jbossModes = jbossModes;
    }

    public ProcessGroupMetadata awsLambdaFunctionNames(List<String> awsLambdaFunctionNames) {
        this.awsLambdaFunctionNames = awsLambdaFunctionNames;
        return this;
    }

    public ProcessGroupMetadata addAwsLambdaFunctionNamesItem(String awsLambdaFunctionNamesItem) {
        if (this.awsLambdaFunctionNames == null) {
            this.awsLambdaFunctionNames = new ArrayList<>();
        }
        this.awsLambdaFunctionNames.add(awsLambdaFunctionNamesItem);
        return this;
    }

    /**
     * @return awsLambdaFunctionNames
     **/
    public List<String> getAwsLambdaFunctionNames() {
        return awsLambdaFunctionNames;
    }

    public void setAwsLambdaFunctionNames(List<String> awsLambdaFunctionNames) {
        this.awsLambdaFunctionNames = awsLambdaFunctionNames;
    }

    public ProcessGroupMetadata cloudFoundryInstanceIndexes(List<String> cloudFoundryInstanceIndexes) {
        this.cloudFoundryInstanceIndexes = cloudFoundryInstanceIndexes;
        return this;
    }

    public ProcessGroupMetadata addCloudFoundryInstanceIndexesItem(String cloudFoundryInstanceIndexesItem) {
        if (this.cloudFoundryInstanceIndexes == null) {
            this.cloudFoundryInstanceIndexes = new ArrayList<>();
        }
        this.cloudFoundryInstanceIndexes.add(cloudFoundryInstanceIndexesItem);
        return this;
    }

    /**
     * @return cloudFoundryInstanceIndexes
     **/
    public List<String> getCloudFoundryInstanceIndexes() {
        return cloudFoundryInstanceIndexes;
    }

    public void setCloudFoundryInstanceIndexes(List<String> cloudFoundryInstanceIndexes) {
        this.cloudFoundryInstanceIndexes = cloudFoundryInstanceIndexes;
    }

    public ProcessGroupMetadata hybrisBinDirectories(List<String> hybrisBinDirectories) {
        this.hybrisBinDirectories = hybrisBinDirectories;
        return this;
    }

    public ProcessGroupMetadata addHybrisBinDirectoriesItem(String hybrisBinDirectoriesItem) {
        if (this.hybrisBinDirectories == null) {
            this.hybrisBinDirectories = new ArrayList<>();
        }
        this.hybrisBinDirectories.add(hybrisBinDirectoriesItem);
        return this;
    }

    /**
     * @return hybrisBinDirectories
     **/
    public List<String> getHybrisBinDirectories() {
        return hybrisBinDirectories;
    }

    public void setHybrisBinDirectories(List<String> hybrisBinDirectories) {
        this.hybrisBinDirectories = hybrisBinDirectories;
    }

    public ProcessGroupMetadata weblogicHomeValues(List<String> weblogicHomeValues) {
        this.weblogicHomeValues = weblogicHomeValues;
        return this;
    }

    public ProcessGroupMetadata addWeblogicHomeValuesItem(String weblogicHomeValuesItem) {
        if (this.weblogicHomeValues == null) {
            this.weblogicHomeValues = new ArrayList<>();
        }
        this.weblogicHomeValues.add(weblogicHomeValuesItem);
        return this;
    }

    /**
     * @return weblogicHomeValues
     **/
    public List<String> getWeblogicHomeValues() {
        return weblogicHomeValues;
    }

    public void setWeblogicHomeValues(List<String> weblogicHomeValues) {
        this.weblogicHomeValues = weblogicHomeValues;
    }

    public ProcessGroupMetadata jbossHomes(List<String> jbossHomes) {
        this.jbossHomes = jbossHomes;
        return this;
    }

    public ProcessGroupMetadata addJbossHomesItem(String jbossHomesItem) {
        if (this.jbossHomes == null) {
            this.jbossHomes = new ArrayList<>();
        }
        this.jbossHomes.add(jbossHomesItem);
        return this;
    }

    /**
     * @return jbossHomes
     **/
    public List<String> getJbossHomes() {
        return jbossHomes;
    }

    public void setJbossHomes(List<String> jbossHomes) {
        this.jbossHomes = jbossHomes;
    }

    public ProcessGroupMetadata dynatraceClusterIds(List<String> dynatraceClusterIds) {
        this.dynatraceClusterIds = dynatraceClusterIds;
        return this;
    }

    public ProcessGroupMetadata addDynatraceClusterIdsItem(String dynatraceClusterIdsItem) {
        if (this.dynatraceClusterIds == null) {
            this.dynatraceClusterIds = new ArrayList<>();
        }
        this.dynatraceClusterIds.add(dynatraceClusterIdsItem);
        return this;
    }

    /**
     * @return dynatraceClusterIds
     **/
    public List<String> getDynatraceClusterIds() {
        return dynatraceClusterIds;
    }

    public void setDynatraceClusterIds(List<String> dynatraceClusterIds) {
        this.dynatraceClusterIds = dynatraceClusterIds;
    }

    public ProcessGroupMetadata googleAppEngineInstances(List<String> googleAppEngineInstances) {
        this.googleAppEngineInstances = googleAppEngineInstances;
        return this;
    }

    public ProcessGroupMetadata addGoogleAppEngineInstancesItem(String googleAppEngineInstancesItem) {
        if (this.googleAppEngineInstances == null) {
            this.googleAppEngineInstances = new ArrayList<>();
        }
        this.googleAppEngineInstances.add(googleAppEngineInstancesItem);
        return this;
    }

    /**
     * @return googleAppEngineInstances
     **/
    public List<String> getGoogleAppEngineInstances() {
        return googleAppEngineInstances;
    }

    public void setGoogleAppEngineInstances(List<String> googleAppEngineInstances) {
        this.googleAppEngineInstances = googleAppEngineInstances;
    }

    public ProcessGroupMetadata commandLineArgs(List<String> commandLineArgs) {
        this.commandLineArgs = commandLineArgs;
        return this;
    }

    public ProcessGroupMetadata addCommandLineArgsItem(String commandLineArgsItem) {
        if (this.commandLineArgs == null) {
            this.commandLineArgs = new ArrayList<>();
        }
        this.commandLineArgs.add(commandLineArgsItem);
        return this;
    }

    /**
     * @return commandLineArgs
     **/
    public List<String> getCommandLineArgs() {
        return commandLineArgs;
    }

    public void setCommandLineArgs(List<String> commandLineArgs) {
        this.commandLineArgs = commandLineArgs;
    }

    public ProcessGroupMetadata aspDotNetCoreApplicationPaths(List<String> aspDotNetCoreApplicationPaths) {
        this.aspDotNetCoreApplicationPaths = aspDotNetCoreApplicationPaths;
        return this;
    }

    public ProcessGroupMetadata addAspDotNetCoreApplicationPathsItem(String aspDotNetCoreApplicationPathsItem) {
        if (this.aspDotNetCoreApplicationPaths == null) {
            this.aspDotNetCoreApplicationPaths = new ArrayList<>();
        }
        this.aspDotNetCoreApplicationPaths.add(aspDotNetCoreApplicationPathsItem);
        return this;
    }

    /**
     * @return aspDotNetCoreApplicationPaths
     **/
    public List<String> getAspDotNetCoreApplicationPaths() {
        return aspDotNetCoreApplicationPaths;
    }

    public void setAspDotNetCoreApplicationPaths(List<String> aspDotNetCoreApplicationPaths) {
        this.aspDotNetCoreApplicationPaths = aspDotNetCoreApplicationPaths;
    }

    public ProcessGroupMetadata awsEcrImageAccountIds(List<String> awsEcrImageAccountIds) {
        this.awsEcrImageAccountIds = awsEcrImageAccountIds;
        return this;
    }

    public ProcessGroupMetadata addAwsEcrImageAccountIdsItem(String awsEcrImageAccountIdsItem) {
        if (this.awsEcrImageAccountIds == null) {
            this.awsEcrImageAccountIds = new ArrayList<>();
        }
        this.awsEcrImageAccountIds.add(awsEcrImageAccountIdsItem);
        return this;
    }

    /**
     * @return awsEcrImageAccountIds
     **/
    public List<String> getAwsEcrImageAccountIds() {
        return awsEcrImageAccountIds;
    }

    public void setAwsEcrImageAccountIds(List<String> awsEcrImageAccountIds) {
        this.awsEcrImageAccountIds = awsEcrImageAccountIds;
    }

    public ProcessGroupMetadata websphereClusterNames(List<String> websphereClusterNames) {
        this.websphereClusterNames = websphereClusterNames;
        return this;
    }

    public ProcessGroupMetadata addWebsphereClusterNamesItem(String websphereClusterNamesItem) {
        if (this.websphereClusterNames == null) {
            this.websphereClusterNames = new ArrayList<>();
        }
        this.websphereClusterNames.add(websphereClusterNamesItem);
        return this;
    }

    /**
     * @return websphereClusterNames
     **/
    public List<String> getWebsphereClusterNames() {
        return websphereClusterNames;
    }

    public void setWebsphereClusterNames(List<String> websphereClusterNames) {
        this.websphereClusterNames = websphereClusterNames;
    }

    public ProcessGroupMetadata kubernetesAnnotations(Map<String, String> kubernetesAnnotations) {
        this.kubernetesAnnotations = kubernetesAnnotations;
        return this;
    }

    public ProcessGroupMetadata putKubernetesAnnotationsItem(String key, String kubernetesAnnotationsItem) {
        if (this.kubernetesAnnotations == null) {
            this.kubernetesAnnotations = new HashMap<>();
        }
        this.kubernetesAnnotations.put(key, kubernetesAnnotationsItem);
        return this;
    }

    /**
     * @return kubernetesAnnotations
     **/
    public Map<String, String> getKubernetesAnnotations() {
        return kubernetesAnnotations;
    }

    public void setKubernetesAnnotations(Map<String, String> kubernetesAnnotations) {
        this.kubernetesAnnotations = kubernetesAnnotations;
    }

    public ProcessGroupMetadata websphereServerNames(List<String> websphereServerNames) {
        this.websphereServerNames = websphereServerNames;
        return this;
    }

    public ProcessGroupMetadata addWebsphereServerNamesItem(String websphereServerNamesItem) {
        if (this.websphereServerNames == null) {
            this.websphereServerNames = new ArrayList<>();
        }
        this.websphereServerNames.add(websphereServerNamesItem);
        return this;
    }

    /**
     * @return websphereServerNames
     **/
    public List<String> getWebsphereServerNames() {
        return websphereServerNames;
    }

    public void setWebsphereServerNames(List<String> websphereServerNames) {
        this.websphereServerNames = websphereServerNames;
    }

    public ProcessGroupMetadata catalinaHomeValues(List<String> catalinaHomeValues) {
        this.catalinaHomeValues = catalinaHomeValues;
        return this;
    }

    public ProcessGroupMetadata addCatalinaHomeValuesItem(String catalinaHomeValuesItem) {
        if (this.catalinaHomeValues == null) {
            this.catalinaHomeValues = new ArrayList<>();
        }
        this.catalinaHomeValues.add(catalinaHomeValuesItem);
        return this;
    }

    /**
     * @return catalinaHomeValues
     **/
    public List<String> getCatalinaHomeValues() {
        return catalinaHomeValues;
    }

    public void setCatalinaHomeValues(List<String> catalinaHomeValues) {
        this.catalinaHomeValues = catalinaHomeValues;
    }

    public ProcessGroupMetadata glassfishDomainNames(List<String> glassfishDomainNames) {
        this.glassfishDomainNames = glassfishDomainNames;
        return this;
    }

    public ProcessGroupMetadata addGlassfishDomainNamesItem(String glassfishDomainNamesItem) {
        if (this.glassfishDomainNames == null) {
            this.glassfishDomainNames = new ArrayList<>();
        }
        this.glassfishDomainNames.add(glassfishDomainNamesItem);
        return this;
    }

    /**
     * @return glassfishDomainNames
     **/
    public List<String> getGlassfishDomainNames() {
        return glassfishDomainNames;
    }

    public void setGlassfishDomainNames(List<String> glassfishDomainNames) {
        this.glassfishDomainNames = glassfishDomainNames;
    }

    public ProcessGroupMetadata kubernetesBasePodNames(List<String> kubernetesBasePodNames) {
        this.kubernetesBasePodNames = kubernetesBasePodNames;
        return this;
    }

    public ProcessGroupMetadata addKubernetesBasePodNamesItem(String kubernetesBasePodNamesItem) {
        if (this.kubernetesBasePodNames == null) {
            this.kubernetesBasePodNames = new ArrayList<>();
        }
        this.kubernetesBasePodNames.add(kubernetesBasePodNamesItem);
        return this;
    }

    /**
     * @return kubernetesBasePodNames
     **/
    public List<String> getKubernetesBasePodNames() {
        return kubernetesBasePodNames;
    }

    public void setKubernetesBasePodNames(List<String> kubernetesBasePodNames) {
        this.kubernetesBasePodNames = kubernetesBasePodNames;
    }

    public ProcessGroupMetadata weblogicClusterNames(List<String> weblogicClusterNames) {
        this.weblogicClusterNames = weblogicClusterNames;
        return this;
    }

    public ProcessGroupMetadata addWeblogicClusterNamesItem(String weblogicClusterNamesItem) {
        if (this.weblogicClusterNames == null) {
            this.weblogicClusterNames = new ArrayList<>();
        }
        this.weblogicClusterNames.add(weblogicClusterNamesItem);
        return this;
    }

    /**
     * @return weblogicClusterNames
     **/
    public List<String> getWeblogicClusterNames() {
        return weblogicClusterNames;
    }

    public void setWeblogicClusterNames(List<String> weblogicClusterNames) {
        this.weblogicClusterNames = weblogicClusterNames;
    }

    public ProcessGroupMetadata websphereNodeNames(List<String> websphereNodeNames) {
        this.websphereNodeNames = websphereNodeNames;
        return this;
    }

    public ProcessGroupMetadata addWebsphereNodeNamesItem(String websphereNodeNamesItem) {
        if (this.websphereNodeNames == null) {
            this.websphereNodeNames = new ArrayList<>();
        }
        this.websphereNodeNames.add(websphereNodeNamesItem);
        return this;
    }

    /**
     * @return websphereNodeNames
     **/
    public List<String> getWebsphereNodeNames() {
        return websphereNodeNames;
    }

    public void setWebsphereNodeNames(List<String> websphereNodeNames) {
        this.websphereNodeNames = websphereNodeNames;
    }

    public ProcessGroupMetadata iisAppPools(List<String> iisAppPools) {
        this.iisAppPools = iisAppPools;
        return this;
    }

    public ProcessGroupMetadata addIisAppPoolsItem(String iisAppPoolsItem) {
        if (this.iisAppPools == null) {
            this.iisAppPools = new ArrayList<>();
        }
        this.iisAppPools.add(iisAppPoolsItem);
        return this;
    }

    /**
     * @return iisAppPools
     **/
    public List<String> getIisAppPools() {
        return iisAppPools;
    }

    public void setIisAppPools(List<String> iisAppPools) {
        this.iisAppPools = iisAppPools;
    }

    public ProcessGroupMetadata javaMainModules(List<String> javaMainModules) {
        this.javaMainModules = javaMainModules;
        return this;
    }

    public ProcessGroupMetadata addJavaMainModulesItem(String javaMainModulesItem) {
        if (this.javaMainModules == null) {
            this.javaMainModules = new ArrayList<>();
        }
        this.javaMainModules.add(javaMainModulesItem);
        return this;
    }

    /**
     * @return javaMainModules
     **/
    public List<String> getJavaMainModules() {
        return javaMainModules;
    }

    public void setJavaMainModules(List<String> javaMainModules) {
        this.javaMainModules = javaMainModules;
    }

    public ProcessGroupMetadata kubernetesPodUids(List<String> kubernetesPodUids) {
        this.kubernetesPodUids = kubernetesPodUids;
        return this;
    }

    public ProcessGroupMetadata addKubernetesPodUidsItem(String kubernetesPodUidsItem) {
        if (this.kubernetesPodUids == null) {
            this.kubernetesPodUids = new ArrayList<>();
        }
        this.kubernetesPodUids.add(kubernetesPodUidsItem);
        return this;
    }

    /**
     * @return kubernetesPodUids
     **/
    public List<String> getKubernetesPodUids() {
        return kubernetesPodUids;
    }

    public void setKubernetesPodUids(List<String> kubernetesPodUids) {
        this.kubernetesPodUids = kubernetesPodUids;
    }

    public ProcessGroupMetadata dockerContainerImageNames(List<String> dockerContainerImageNames) {
        this.dockerContainerImageNames = dockerContainerImageNames;
        return this;
    }

    public ProcessGroupMetadata addDockerContainerImageNamesItem(String dockerContainerImageNamesItem) {
        if (this.dockerContainerImageNames == null) {
            this.dockerContainerImageNames = new ArrayList<>();
        }
        this.dockerContainerImageNames.add(dockerContainerImageNamesItem);
        return this;
    }

    /**
     * @return dockerContainerImageNames
     **/
    public List<String> getDockerContainerImageNames() {
        return dockerContainerImageNames;
    }

    public void setDockerContainerImageNames(List<String> dockerContainerImageNames) {
        this.dockerContainerImageNames = dockerContainerImageNames;
    }

    public ProcessGroupMetadata coldfusionJvmConfigFiles(List<String> coldfusionJvmConfigFiles) {
        this.coldfusionJvmConfigFiles = coldfusionJvmConfigFiles;
        return this;
    }

    public ProcessGroupMetadata addColdfusionJvmConfigFilesItem(String coldfusionJvmConfigFilesItem) {
        if (this.coldfusionJvmConfigFiles == null) {
            this.coldfusionJvmConfigFiles = new ArrayList<>();
        }
        this.coldfusionJvmConfigFiles.add(coldfusionJvmConfigFilesItem);
        return this;
    }

    /**
     * @return coldfusionJvmConfigFiles
     **/
    public List<String> getColdfusionJvmConfigFiles() {
        return coldfusionJvmConfigFiles;
    }

    public void setColdfusionJvmConfigFiles(List<String> coldfusionJvmConfigFiles) {
        this.coldfusionJvmConfigFiles = coldfusionJvmConfigFiles;
    }

    public ProcessGroupMetadata serviceNames(List<String> serviceNames) {
        this.serviceNames = serviceNames;
        return this;
    }

    public ProcessGroupMetadata addServiceNamesItem(String serviceNamesItem) {
        if (this.serviceNames == null) {
            this.serviceNames = new ArrayList<>();
        }
        this.serviceNames.add(serviceNamesItem);
        return this;
    }

    /**
     * @return serviceNames
     **/
    public List<String> getServiceNames() {
        return serviceNames;
    }

    public void setServiceNames(List<String> serviceNames) {
        this.serviceNames = serviceNames;
    }

    public ProcessGroupMetadata dotnetCommandPath(List<String> dotnetCommandPath) {
        this.dotnetCommandPath = dotnetCommandPath;
        return this;
    }

    public ProcessGroupMetadata addDotnetCommandPathItem(String dotnetCommandPathItem) {
        if (this.dotnetCommandPath == null) {
            this.dotnetCommandPath = new ArrayList<>();
        }
        this.dotnetCommandPath.add(dotnetCommandPathItem);
        return this;
    }

    /**
     * @return dotnetCommandPath
     **/
    public List<String> getDotnetCommandPath() {
        return dotnetCommandPath;
    }

    public void setDotnetCommandPath(List<String> dotnetCommandPath) {
        this.dotnetCommandPath = dotnetCommandPath;
    }

    public ProcessGroupMetadata ibmIntegrationBusExecutionGroupNames(List<String> ibmIntegrationBusExecutionGroupNames) {
        this.ibmIntegrationBusExecutionGroupNames = ibmIntegrationBusExecutionGroupNames;
        return this;
    }

    public ProcessGroupMetadata addIbmIntegrationBusExecutionGroupNamesItem(String ibmIntegrationBusExecutionGroupNamesItem) {
        if (this.ibmIntegrationBusExecutionGroupNames == null) {
            this.ibmIntegrationBusExecutionGroupNames = new ArrayList<>();
        }
        this.ibmIntegrationBusExecutionGroupNames.add(ibmIntegrationBusExecutionGroupNamesItem);
        return this;
    }

    /**
     * @return ibmIntegrationBusExecutionGroupNames
     **/
    public List<String> getIbmIntegrationBusExecutionGroupNames() {
        return ibmIntegrationBusExecutionGroupNames;
    }

    public void setIbmIntegrationBusExecutionGroupNames(List<String> ibmIntegrationBusExecutionGroupNames) {
        this.ibmIntegrationBusExecutionGroupNames = ibmIntegrationBusExecutionGroupNames;
    }

    public ProcessGroupMetadata websphereCellNames(List<String> websphereCellNames) {
        this.websphereCellNames = websphereCellNames;
        return this;
    }

    public ProcessGroupMetadata addWebsphereCellNamesItem(String websphereCellNamesItem) {
        if (this.websphereCellNames == null) {
            this.websphereCellNames = new ArrayList<>();
        }
        this.websphereCellNames.add(websphereCellNamesItem);
        return this;
    }

    /**
     * @return websphereCellNames
     **/
    public List<String> getWebsphereCellNames() {
        return websphereCellNames;
    }

    public void setWebsphereCellNames(List<String> websphereCellNames) {
        this.websphereCellNames = websphereCellNames;
    }

    public ProcessGroupMetadata elasticSearchClusterNames(List<String> elasticSearchClusterNames) {
        this.elasticSearchClusterNames = elasticSearchClusterNames;
        return this;
    }

    public ProcessGroupMetadata addElasticSearchClusterNamesItem(String elasticSearchClusterNamesItem) {
        if (this.elasticSearchClusterNames == null) {
            this.elasticSearchClusterNames = new ArrayList<>();
        }
        this.elasticSearchClusterNames.add(elasticSearchClusterNamesItem);
        return this;
    }

    /**
     * @return elasticSearchClusterNames
     **/
    public List<String> getElasticSearchClusterNames() {
        return elasticSearchClusterNames;
    }

    public void setElasticSearchClusterNames(List<String> elasticSearchClusterNames) {
        this.elasticSearchClusterNames = elasticSearchClusterNames;
    }

    public ProcessGroupMetadata nodejsAppNames(List<String> nodejsAppNames) {
        this.nodejsAppNames = nodejsAppNames;
        return this;
    }

    public ProcessGroupMetadata addNodejsAppNamesItem(String nodejsAppNamesItem) {
        if (this.nodejsAppNames == null) {
            this.nodejsAppNames = new ArrayList<>();
        }
        this.nodejsAppNames.add(nodejsAppNamesItem);
        return this;
    }

    /**
     * @return nodejsAppNames
     **/
    public List<String> getNodejsAppNames() {
        return nodejsAppNames;
    }

    public void setNodejsAppNames(List<String> nodejsAppNames) {
        this.nodejsAppNames = nodejsAppNames;
    }

    public ProcessGroupMetadata nodejsScriptNames(List<String> nodejsScriptNames) {
        this.nodejsScriptNames = nodejsScriptNames;
        return this;
    }

    public ProcessGroupMetadata addNodejsScriptNamesItem(String nodejsScriptNamesItem) {
        if (this.nodejsScriptNames == null) {
            this.nodejsScriptNames = new ArrayList<>();
        }
        this.nodejsScriptNames.add(nodejsScriptNamesItem);
        return this;
    }

    /**
     * @return nodejsScriptNames
     **/
    public List<String> getNodejsScriptNames() {
        return nodejsScriptNames;
    }

    public void setNodejsScriptNames(List<String> nodejsScriptNames) {
        this.nodejsScriptNames = nodejsScriptNames;
    }

    public ProcessGroupMetadata iisRoleNames(List<String> iisRoleNames) {
        this.iisRoleNames = iisRoleNames;
        return this;
    }

    public ProcessGroupMetadata addIisRoleNamesItem(String iisRoleNamesItem) {
        if (this.iisRoleNames == null) {
            this.iisRoleNames = new ArrayList<>();
        }
        this.iisRoleNames.add(iisRoleNamesItem);
        return this;
    }

    /**
     * @return iisRoleNames
     **/
    public List<String> getIisRoleNames() {
        return iisRoleNames;
    }

    public void setIisRoleNames(List<String> iisRoleNames) {
        this.iisRoleNames = iisRoleNames;
    }

    public ProcessGroupMetadata apacheSparkMasterIpAddresses(List<String> apacheSparkMasterIpAddresses) {
        this.apacheSparkMasterIpAddresses = apacheSparkMasterIpAddresses;
        return this;
    }

    public ProcessGroupMetadata addApacheSparkMasterIpAddressesItem(String apacheSparkMasterIpAddressesItem) {
        if (this.apacheSparkMasterIpAddresses == null) {
            this.apacheSparkMasterIpAddresses = new ArrayList<>();
        }
        this.apacheSparkMasterIpAddresses.add(apacheSparkMasterIpAddressesItem);
        return this;
    }

    /**
     * @return apacheSparkMasterIpAddresses
     **/
    public List<String> getApacheSparkMasterIpAddresses() {
        return apacheSparkMasterIpAddresses;
    }

    public void setApacheSparkMasterIpAddresses(List<String> apacheSparkMasterIpAddresses) {
        this.apacheSparkMasterIpAddresses = apacheSparkMasterIpAddresses;
    }

    public ProcessGroupMetadata weblogicNames(List<String> weblogicNames) {
        this.weblogicNames = weblogicNames;
        return this;
    }

    public ProcessGroupMetadata addWeblogicNamesItem(String weblogicNamesItem) {
        if (this.weblogicNames == null) {
            this.weblogicNames = new ArrayList<>();
        }
        this.weblogicNames.add(weblogicNamesItem);
        return this;
    }

    /**
     * @return weblogicNames
     **/
    public List<String> getWeblogicNames() {
        return weblogicNames;
    }

    public void setWeblogicNames(List<String> weblogicNames) {
        this.weblogicNames = weblogicNames;
    }

    public ProcessGroupMetadata rubyScriptPaths(List<String> rubyScriptPaths) {
        this.rubyScriptPaths = rubyScriptPaths;
        return this;
    }

    public ProcessGroupMetadata addRubyScriptPathsItem(String rubyScriptPathsItem) {
        if (this.rubyScriptPaths == null) {
            this.rubyScriptPaths = new ArrayList<>();
        }
        this.rubyScriptPaths.add(rubyScriptPathsItem);
        return this;
    }

    /**
     * @return rubyScriptPaths
     **/
    public List<String> getRubyScriptPaths() {
        return rubyScriptPaths;
    }

    public void setRubyScriptPaths(List<String> rubyScriptPaths) {
        this.rubyScriptPaths = rubyScriptPaths;
    }

    public ProcessGroupMetadata awsRegions(List<String> awsRegions) {
        this.awsRegions = awsRegions;
        return this;
    }

    public ProcessGroupMetadata addAwsRegionsItem(String awsRegionsItem) {
        if (this.awsRegions == null) {
            this.awsRegions = new ArrayList<>();
        }
        this.awsRegions.add(awsRegionsItem);
        return this;
    }

    /**
     * @return awsRegions
     **/
    public List<String> getAwsRegions() {
        return awsRegions;
    }

    public void setAwsRegions(List<String> awsRegions) {
        this.awsRegions = awsRegions;
    }

    @Override
    public String toString() {
        return "class ProcessGroupMetadata {\n"
                + "    nodejsAppBaseDirectories: " + toIndentedString(nodejsAppBaseDirectories) + "\n"
                + "    hostGroups: " + toIndentedString(hostGroups) + "\n"
                + "    cloudFoundryAppIds: " + toIndentedString(cloudFoundryAppIds) + "\n"
                + "    dynatraceNodeIds: " + toIndentedString(dynatraceNodeIds) + "\n"
                + "    executables: " + toIndentedString(executables) + "\n"
                + "    javaMainClasses: " + toIndentedString(javaMainClasses) + "\n"
                + "    cassandraClusterNames: " + toIndentedString(cassandraClusterNames) + "\n"
                + "    cloudFoundryAppNames: " + toIndentedString(cloudFoundryAppNames) + "\n"
                + "    cloudFoundrySpaceNames: " + toIndentedString(cloudFoundrySpaceNames) + "\n"
                + "    phpScripts: " + toIndentedString(phpScripts) + "\n"
                + "    pluginMetadata: " + toIndentedString(pluginMetadata) + "\n"
                + "    dockerContainerNames: " + toIndentedString(dockerContainerNames) + "\n"
                + "    glassfishInstanceNames: " + toIndentedString(glassfishInstanceNames) + "\n"
                + "    tibcoBusinessWorksEnginePropertyFiles: " + toIndentedString(tibcoBusinessWorksEnginePropertyFiles) + "\n"
                + "    jbossServerNames: " + toIndentedString(jbossServerNames) + "\n"
                + "    catalinaBaseValues: " + toIndentedString(catalinaBaseValues) + "\n"
                + "    kubernetesFullPodNames: " + toIndentedString(kubernetesFullPodNames) + "\n"
                + "    apacheConfigPaths: " + toIndentedString(apacheConfigPaths) + "\n"
                + "    varnishInstanceNames: " + toIndentedString(varnishInstanceNames) + "\n"
                + "    phpWorkingDirectories: " + toIndentedString(phpWorkingDirectories) + "\n"
                + "    googleCloudProjects: " + toIndentedString(googleCloudProjects) + "\n"
                + "    dockerContainerImageVersions: " + toIndentedString(dockerContainerImageVersions) + "\n"
                + "    hybrisConfigDirectories: " + toIndentedString(hybrisConfigDirectories) + "\n"
                + "    executablePaths: " + toIndentedString(executablePaths) + "\n"
                + "    awsEcrImageRegions: " + toIndentedString(awsEcrImageRegions) + "\n"
                + "    dotNetCommands: " + toIndentedString(dotNetCommands) + "\n"
                + "    weblogicDomainNames: " + toIndentedString(weblogicDomainNames) + "\n"
                + "    googleAppEngineServices: " + toIndentedString(googleAppEngineServices) + "\n"
                + "    ibmIntegrationBusBrokerNames: " + toIndentedString(ibmIntegrationBusBrokerNames) + "\n"
                + "    elasticSearchNodeNames: " + toIndentedString(elasticSearchNodeNames) + "\n"
                + "    kubernetesNamespaces: " + toIndentedString(kubernetesNamespaces) + "\n"
                + "    hybrisDataDirectories: " + toIndentedString(hybrisDataDirectories) + "\n"
                + "    envVariables: " + toIndentedString(envVariables) + "\n"
                + "    javaJarFiles: " + toIndentedString(javaJarFiles) + "\n"
                + "    javaJarPaths: " + toIndentedString(javaJarPaths) + "\n"
                + "    dockerContainerIds: " + toIndentedString(dockerContainerIds) + "\n"
                + "    cloudFoundrySpaceIds: " + toIndentedString(cloudFoundrySpaceIds) + "\n"
                + "    tibcoBWEnginePropertyFilePaths: " + toIndentedString(tibcoBWEnginePropertyFilePaths) + "\n"
                + "    kubernetesContainerNames: " + toIndentedString(kubernetesContainerNames) + "\n"
                + "    ruleResult: " + toIndentedString(ruleResult) + "\n"
                + "    rubyAppRootPaths: " + toIndentedString(rubyAppRootPaths) + "\n"
                + "    jbossModes: " + toIndentedString(jbossModes) + "\n"
                + "    awsLambdaFunctionNames: " + toIndentedString(awsLambdaFunctionNames) + "\n"
                + "    cloudFoundryInstanceIndexes: " + toIndentedString(cloudFoundryInstanceIndexes) + "\n"
                + "    hybrisBinDirectories: " + toIndentedString(hybrisBinDirectories) + "\n"
                + "    weblogicHomeValues: " + toIndentedString(weblogicHomeValues) + "\n"
                + "    jbossHomes: " + toIndentedString(jbossHomes) + "\n"
                + "    dynatraceClusterIds: " + toIndentedString(dynatraceClusterIds) + "\n"
                + "    googleAppEngineInstances: " + toIndentedString(googleAppEngineInstances) + "\n"
                + "    commandLineArgs: " + toIndentedString(commandLineArgs) + "\n"
                + "    aspDotNetCoreApplicationPaths: " + toIndentedString(aspDotNetCoreApplicationPaths) + "\n"
                + "    awsEcrImageAccountIds: " + toIndentedString(awsEcrImageAccountIds) + "\n"
                + "    websphereClusterNames: " + toIndentedString(websphereClusterNames) + "\n"
                + "    kubernetesAnnotations: " + toIndentedString(kubernetesAnnotations) + "\n"
                + "    websphereServerNames: " + toIndentedString(websphereServerNames) + "\n"
                + "    catalinaHomeValues: " + toIndentedString(catalinaHomeValues) + "\n"
                + "    glassfishDomainNames: " + toIndentedString(glassfishDomainNames) + "\n"
                + "    kubernetesBasePodNames: " + toIndentedString(kubernetesBasePodNames) + "\n"
                + "    weblogicClusterNames: " + toIndentedString(weblogicClusterNames) + "\n"
                + "    websphereNodeNames: " + toIndentedString(websphereNodeNames) + "\n"
                + "    iisAppPools: " + toIndentedString(iisAppPools) + "\n"
                + "    javaMainModules: " + toIndentedString(javaMainModules) + "\n"
                + "    kubernetesPodUids: " + toIndentedString(kubernetesPodUids) + "\n"
                + "    dockerContainerImageNames: " + toIndentedString(dockerContainerImageNames) + "\n"
                + "    coldfusionJvmConfigFiles: " + toIndentedString(coldfusionJvmConfigFiles) + "\n"
                + "    serviceNames: " + toIndentedString(serviceNames) + "\n"
                + "    dotnetCommandPath: " + toIndentedString(dotnetCommandPath) + "\n"
                + "    ibmIntegrationBusExecutionGroupNames: " + toIndentedString(ibmIntegrationBusExecutionGroupNames) + "\n"
                + "    websphereCellNames: " + toIndentedString(websphereCellNames) + "\n"
                + "    elasticSearchClusterNames: " + toIndentedString(elasticSearchClusterNames) + "\n"
                + "    nodejsAppNames: " + toIndentedString(nodejsAppNames) + "\n"
                + "    nodejsScriptNames: " + toIndentedString(nodejsScriptNames) + "\n"
                + "    iisRoleNames: " + toIndentedString(iisRoleNames) + "\n"
                + "    apacheSparkMasterIpAddresses: " + toIndentedString(apacheSparkMasterIpAddresses) + "\n"
                + "    weblogicNames: " + toIndentedString(weblogicNames) + "\n"
                + "    rubyScriptPaths: " + toIndentedString(rubyScriptPaths) + "\n"
                + "    awsRegions: " + toIndentedString(awsRegions) + "\n"
                + "}";
    }
}

