/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * SyntheticStepError
 */

public class SyntheticStepError {
    @SerializedName("message")
    private String message;

    @SerializedName("code")
    private Integer code;

    public SyntheticStepError message(String message) {
        this.message = message;
        return this;
    }

    /**
     * The error message.
     *
     * @return message
     **/
    @ApiModelProperty(required = true, value = "The error message.")
    public String getMessage() {
        return message;
    }

    public void setMessage(String message) {
        this.message = message;
    }

    public SyntheticStepError code(Integer code) {
        this.code = code;
        return this;
    }

    /**
     * The error code in case the execution of the step failed.
     *
     * @return code
     **/
    @ApiModelProperty(required = true, value = "The error code in case the execution of the step failed.")
    public Integer getCode() {
        return code;
    }

    public void setCode(Integer code) {
        this.code = code;
    }

    @Override
    public String toString() {
        return "class SyntheticStepError {\n" +
                "    message: " + toIndentedString(message) + "\n" +
                "    code: " + toIndentedString(code) + "\n" +
                "}";
    }
}

