/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * Synthetic location
 */
@ApiModel(description = "Synthetic location")

public class SyntheticLocation {
    @SerializedName("id")
    private String id = null;

    @SerializedName("name")
    private String name = null;

    @SerializedName("ip")
    private String ip = null;

    @SerializedName("iconUrl")
    private String iconUrl = null;

    public SyntheticLocation id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Unique id which identifies the location.
     *
     * @return id
     **/
    @ApiModelProperty(required = true, value = "Unique id which identifies the location.")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public SyntheticLocation name(String name) {
        this.name = name;
        return this;
    }

    /**
     * Location display name.
     *
     * @return name
     **/
    @ApiModelProperty(value = "Location display name.")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public SyntheticLocation ip(String ip) {
        this.ip = ip;
        return this;
    }

    /**
     * Location ip address.
     *
     * @return ip
     **/
    @ApiModelProperty(required = true, value = "Location ip address.")
    public String getIp() {
        return ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    public SyntheticLocation iconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
        return this;
    }

    /**
     * Location icon URL.
     *
     * @return iconUrl
     **/
    @ApiModelProperty(value = "Location icon URL.")
    public String getIconUrl() {
        return iconUrl;
    }

    public void setIconUrl(String iconUrl) {
        this.iconUrl = iconUrl;
    }

    @Override
    public String toString() {
        return "class SyntheticLocation {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    name: " + toIndentedString(name) + "\n" +
                "    ip: " + toIndentedString(ip) + "\n" +
                "    iconUrl: " + toIndentedString(iconUrl) + "\n" +
                "}";
    }
}

