/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModelProperty;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * SyntheticTestLocation
 */

public class SyntheticTestLocation {
    @SerializedName("id")
    private String id = null;

    @SerializedName("enabled")
    private Boolean enabled = null;

    public SyntheticTestLocation id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Unique id which identifies the location.
     *
     * @return id
     **/
    @ApiModelProperty(required = true, value = "Unique id which identifies the location.")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public SyntheticTestLocation enabled(Boolean enabled) {
        this.enabled = enabled;
        return this;
    }

    /**
     * True if enabled, false if disabled or deleted, defaults to true.
     *
     * @return enabled
     **/
    @ApiModelProperty(value = "True if enabled, false if disabled or deleted, defaults to true.")
    public Boolean isEnabled() {
        return enabled;
    }

    public void setEnabled(Boolean enabled) {
        this.enabled = enabled;
    }

    @Override
    public String toString() {
        return "class SyntheticTestLocation {\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "    enabled: " + toIndentedString(enabled) + "\n" +
                "}";
    }
}

