/*
 * Copyright (c) 2014-2018 T-Systems Multimedia Solutions GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Dynatrace Environment API
 * Documentation of the Dynatrace REST API. Refer to the [help page](https://www.dynatrace.com/support/help/shortlink/section-api) to read about use-cases and examples.
 *
 * OpenAPI spec version: 1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package de.tsystems.mms.apm.performancesignature.dynatracesaas.rest.model;

import com.google.gson.annotations.SerializedName;
import de.tsystems.mms.apm.performancesignature.dynatracesaas.model.TagInfo;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.ArrayList;
import java.util.List;

import static de.tsystems.mms.apm.performancesignature.ui.util.PerfSigUIUtils.toIndentedString;

/**
 * Single Event that is returned in the Event Feed Query
 */
@ApiModel(description = "Single Event that is returned in the Event Feed Query")

public class EventRestEntry {
    @SerializedName("startTime")
    private Long startTime;

    @SerializedName("endTime")
    private Long endTime;

    @SerializedName("entityId")
    private String entityId;

    @SerializedName("entityName")
    private String entityName;
    @SerializedName("severityLevel")
    private SeverityLevelEnum severityLevel;
    @SerializedName("impactLevel")
    private ImpactLevelEnum impactLevel;
    @SerializedName("eventType")
    private EventTypeEnum eventType;
    @SerializedName("eventStatus")
    private StatusEnum eventStatus;
    @SerializedName("tags")
    private List<TagInfo> tags;
    @SerializedName("id")
    private String id;

    public EventRestEntry startTime(Long startTime) {
        this.startTime = startTime;
        return this;
    }

    /**
     * Timestamp when the event was detected
     *
     * @return startTime
     **/
    @ApiModelProperty(value = "Timestamp when the event was detected")
    public Long getStartTime() {
        return startTime;
    }

    public void setStartTime(Long startTime) {
        this.startTime = startTime;
    }

    public EventRestEntry endTime(Long endTime) {
        this.endTime = endTime;
        return this;
    }

    /**
     * Timestamp when the event was closed
     *
     * @return endTime
     **/
    @ApiModelProperty(value = "Timestamp when the event was closed")
    public Long getEndTime() {
        return endTime;
    }

    public void setEndTime(Long endTime) {
        this.endTime = endTime;
    }

    public EventRestEntry entityId(String entityId) {
        this.entityId = entityId;
        return this;
    }

    /**
     * The ID of the affected Dynatrace entity.    You can find the ID in the URL of the corresponding Dynatrace entity page, for example, &#x60;HOST-007&#x60;.
     *
     * @return entityId
     **/
    @ApiModelProperty(value = "The ID of the affected Dynatrace entity.    You can find the ID in the URL of the corresponding Dynatrace entity page, for example, `HOST-007`.")
    public String getEntityId() {
        return entityId;
    }

    public void setEntityId(String entityId) {
        this.entityId = entityId;
    }

    public EventRestEntry entityName(String entityName) {
        this.entityName = entityName;
        return this;
    }

    /**
     * The name of the affected Dynatrace entity.
     *
     * @return entityName
     **/
    @ApiModelProperty(value = "The name of the affected Dynatrace entity.")
    public String getEntityName() {
        return entityName;
    }

    public void setEntityName(String entityName) {
        this.entityName = entityName;
    }

    public EventRestEntry severityLevel(SeverityLevelEnum severityLevel) {
        this.severityLevel = severityLevel;
        return this;
    }

    /**
     * The severity of the event.
     *
     * @return severityLevel
     **/
    @ApiModelProperty(value = "The severity of the event.")
    public SeverityLevelEnum getSeverityLevel() {
        return severityLevel;
    }

    public void setSeverityLevel(SeverityLevelEnum severityLevel) {
        this.severityLevel = severityLevel;
    }

    public EventRestEntry impactLevel(ImpactLevelEnum impactLevel) {
        this.impactLevel = impactLevel;
        return this;
    }

    /**
     * The impact level of the event.
     *
     * @return impactLevel
     **/
    @ApiModelProperty(value = "The impact level of the event.")
    public ImpactLevelEnum getImpactLevel() {
        return impactLevel;
    }

    public void setImpactLevel(ImpactLevelEnum impactLevel) {
        this.impactLevel = impactLevel;
    }

    public EventRestEntry eventType(EventTypeEnum eventType) {
        this.eventType = eventType;
        return this;
    }

    /**
     * The type of the event.
     *
     * @return eventType
     **/
    @ApiModelProperty(value = "The type of the event.")
    public EventTypeEnum getEventType() {
        return eventType;
    }

    public void setEventType(EventTypeEnum eventType) {
        this.eventType = eventType;
    }

    public EventRestEntry eventStatus(StatusEnum eventStatus) {
        this.eventStatus = eventStatus;
        return this;
    }

    /**
     * Specifies the event state
     *
     * @return eventStatus
     **/
    @ApiModelProperty(value = "Specifies the event state")
    public StatusEnum getEventStatus() {
        return eventStatus;
    }

    public void setEventStatus(StatusEnum eventStatus) {
        this.eventStatus = eventStatus;
    }

    public EventRestEntry tags(List<TagInfo> tags) {
        this.tags = tags;
        return this;
    }

    public EventRestEntry addTagsItem(TagInfo tagsItem) {
        if (this.tags == null) {
            this.tags = new ArrayList<>();
        }
        this.tags.add(tagsItem);
        return this;
    }

    /**
     * Collects all the tags associated with the monitored entity that raises the event
     *
     * @return tags
     **/
    @ApiModelProperty(value = "Collects all the tags associated with the monitored entity that raises the event")
    public List<TagInfo> getTags() {
        return tags;
    }

    public void setTags(List<TagInfo> tags) {
        this.tags = tags;
    }

    public EventRestEntry id(String id) {
        this.id = id;
        return this;
    }

    /**
     * Encoded Event identifier
     *
     * @return id
     **/
    @ApiModelProperty(value = "Encoded Event identifier")
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return "class EventRestEntry {\n" +
                "    startTime: " + toIndentedString(startTime) + "\n" +
                "    endTime: " + toIndentedString(endTime) + "\n" +
                "    entityId: " + toIndentedString(entityId) + "\n" +
                "    entityName: " + toIndentedString(entityName) + "\n" +
                "    severityLevel: " + toIndentedString(severityLevel) + "\n" +
                "    impactLevel: " + toIndentedString(impactLevel) + "\n" +
                "    eventType: " + toIndentedString(eventType) + "\n" +
                "    eventStatus: " + toIndentedString(eventStatus) + "\n" +
                "    tags: " + toIndentedString(tags) + "\n" +
                "    id: " + toIndentedString(id) + "\n" +
                "}";
    }
}

